### ISSUE TITLE
希望能够识别到plus专享价。

### ISSUE THREAD

**Issue by GameXG** [sunoj/jjb#1]
如题，希望先判断是否为plus会员然后确定是否比较 plus专享价。

**Comment by sunoj** [comment]
好建议，欢迎贡献代码

**Comment by GameXG** [comment]
https://github.com/GameXG/jjb/commit/29afd6745f5acbbf22d22f7763c2dc053c0f7c82

试了下，发现查询价格页面未登录...

**Comment by sunoj** [comment]
价格页面未登录不是问题，插件只需要在京东登录后保存一下当前登录的账号的plus与否到 localStorage 就行了

**Comment by GameXG** [comment]
嗯，看了下plus优惠卷页面可以获得是否是plus，这个页面应该是已登陆的，就是依赖于 plus优惠卷页面不太好。
我看看登录流程。

**Comment by GameXG** [comment]
一个奇怪的问题，localStorage 被隔离了？

plus 优惠卷页面设置了 localStorage，商品列表页面读取读取不出来，看起来这个也隔离了。
等有时间用 chrome.storage 做吧。

**Comment by sunoj** [comment]
是啊 localStorage 只在当前域下面生效，如果要用就要用message在中间传， 你用chrome.storage也不改变这一点

**Comment by GameXG** [comment]
额，一直没注意到是不同的子域名...

我记得 content_script 有权限读取 扩展 storage，缺陷是 chrome 和 firefox api 有区别及get是回调实现。
