### ISSUE TITLE
能否减少京价保的自动登录尝试次数？

### ISSUE THREAD

**Issue by TGhoul** [sunoj/jjb#101]
前几天由于京价宝过于频繁的自动登录，引起了京东的安全检查策略，要求我强制修改密码，虽然改改密码就好了，但是担心京价保的自动登录策略会经常引起京东的安全检查策略，导致需要经常的修改密码。

**Comment by TGhoul** [comment]
@sunoj 应该就是最新版的，chrome插件应该是自动更新的，昨天看了一下版本号是1.18.2，情况是这样，京东强制我修改密码，改完密码以后京价保并不知道，然后尝试自动登陆，所以就出现了，十次密码错误，被锁定20分钟，如此往复，京东就又检测出账号存在风险，我觉得只要失败一次，就不要再尝试，这样会比较合适。

**Comment by sunoj** [comment]
修改密码之后在京价保中忘记一下密码。登录政策会再检查一下，应该现在就是登录失败之后不会再试了。

**Comment by TGhoul** [comment]
好的，我会在检查一下的。
