### ISSUE TITLE
频繁登录问题

### ISSUE THREAD

**Issue by cokll** [sunoj/jjb#102]
请详细的描述这个bug的细节

3-6小时需要重新登录一次,包括手机与PC端,且必须输入验证码

Windows 10 17134
京价保版本 1.18.2
浏览器版本 Google Chrome  68.0.3440.106（正式版本） （64 位）

**Comment by iHandle** [comment]
我也遇到了同样的问题
macOS 10.13.6 
京价保版本 1.18.2
浏览器版本 Google Chrome 68.0.3440.106（正式版本） （64 位）

**Comment by sunoj** [comment]
已更新 1.18.3 当登录失败时，下次不会再尝试登录。

**Comment by jdswee** [comment]
仍然频繁登录失败，需要重新登录，版本 2.3.5，操作系统 Windows 10，chrome 72.0.3626.121（正式版本） （64 位）
