### ISSUE TITLE
请问是否有办法在多台电脑上只启用其中一台电脑的京价保？

### ISSUE THREAD

**Issue by aoxu** [sunoj/jjb#103]
由于我的多台电脑都通过Chrome同步了京价保扩展，以至于几台电脑都会用京价保做自动签到等操作，导致争抢登录态，每天都被京东检测到频繁登录然后失去登录态，于是每天都要手动操作填写验证码来登录……
请问是否有办法只启用其中一台电脑的京价保，而关闭其他电脑的京价保功能？谢谢。

**Comment by sunoj** [comment]
你在你不使用的电脑上的京价保高级设置中“清除账号密码”，之后就不会再自动登录和运行了。或者在这些电脑上把所有的任务都改成从不。

**Comment by aoxu** [comment]
明白了，已经按照说明设置，谢谢！
