### ISSUE TITLE
历史价格曲线失踪了

### ISSUE THREAD

**Issue by rexsix** [sunoj/jjb#106]
**Describe the bug**

历史价格曲线失踪了。

**To Reproduce**

访问任何产品，无论第三方还是自营，均不能显示价格曲线（已关闭所有插件），Console未见异常抛错。

每次刷新/打开 商品页面时，可以看到『价格走势』的标题栏出现约1秒后，立即消失不见。

**Expected behavior**

应该和以前一样，可以显示价格历史。

**Screenshots**

![image](https://user-images.githubusercontent.com/9947151/46246552-4e8be500-c432-11e8-8d0a-a8e2585044ee.png)

![image](https://user-images.githubusercontent.com/9947151/46246568-8bf07280-c432-11e8-9e48-8b70fbc3293e.png)

**Desktop (please complete the following information):**

 - OS: MacOS 10.14
 - Browser: Chrome
 - Version: 69.0.3497.100 (Official Build) (64-bit)
 - 京价保：2.0.4

**Additional context**

暂无

**Comment by sunoj** [comment]
由于京东的SKU数量规模庞大，京价保目前SKU覆盖度有限（虽然在快速增长），目前来看暂时还只覆盖了不到2%的商品，例如你截图的这个商品，确实就还未覆盖到。

你试试访问这个商品呢：
https://item.jd.com/851672.html

**Comment by rexsix** [comment]
这个商品看到了，两根曲线（标准价 & plus）。
另外，刚才的牛排的曲线也已经能看到了，只是出奇的慢。
如可能，请作者考虑加入 loading态 或者 告知 暂无数据，兴许会更好。

谢谢！

**Comment by sunoj** [comment]
> 这个商品看到了，两根曲线（标准价 & plus）。
> 另外，刚才的牛排的曲线也已经能看到了，只是出奇地慢。
> 
> 如可能，请作者考虑加入 loading态 或者 告知 暂无数据，兴许会更好。
> 
> 谢谢！

加上了
