### ISSUE TITLE
开启京价保打开网页时会有一定几率跳转到http://traffic.inboxit.ru/9mbWN4

### ISSUE THREAD

**Issue by xuyoji** [sunoj/jjb#107]
这是一个无效的网址。反复试验，关闭京价保不会出现此现象。

**Comment by sunoj** [comment]
是安装的 chrome 官方市场的版本吗？京价保不可能会打开这样的网址，因为代码中根本没这个网址。
目前没有收到的任何类似的报告，能告知一下详情吗？比如打开任意域名的网页都有机会跳转吗？

**Comment by sunoj** [comment]
我搜索了一下，请你检查一下有没有装过这个拓展：Video Downloader Pro

**Comment by xuyoji** [comment]
> 我搜索了一下，请你检查一下有没有装过这个拓展：Video Downloader Pro
刚看了下，是安装了这个软件。主要是京东和小米出现跳转的概率比较大，其他也有。我再做下测试，是不看下是不是跟京价保有冲突。

**Comment by sunoj** [comment]
“是不是跟京价保有冲突”是指什么意思？请务必了解：京价保绝对没有劫持你的访问，麻烦你仔细调查一下情况。

**Comment by xuyoji** [comment]
> “是不是跟京价保有冲突”是指什么意思？请务必了解：京价保绝对没有劫持你的访问，麻烦你仔细调查一下情况。

emm，我想你误解我的意思了。并没有任何恶意，只是在想是不是京价保是否会无意中诱发了video download pro 这个软件劫持域名的行为。这几天我再做一些测试，感谢你的及时回复。之前在微信转账支持了你的软件，希望以后会做得更棒~

**Comment by sunoj** [comment]
抱歉误解了你的意思，但是确实经常受到类似的“指控”，言之凿凿就是京价保导致的若干问题，最后我还是要帮忙调查情况，希望您理解。

**Comment by sunoj** [comment]
然后我也十分不理解什么叫：“京价保是否会无意中诱发了video download pro 这个软件劫持域名的行为”。

一个恶意软件的恶意行为为什么会被认为是一个正常软件的正常行为“诱发”的？这难道不应该通过卸载恶意软件来解决问题？而是要找正常软件的毛病？

**Comment by xuyoji** [comment]
> 然后我也十分不理解什么叫：“京价保是否会无意中诱发了video download pro 这个软件劫持域名的行为”。
> 
> 一个恶意软件的恶意行为为什么会被认为是一个正常软件的正常行为“诱发”的？这难道不应该通过卸载恶意软件来解决问题？而是要找正常软件的毛病？

到底怎么说大佬您才能不玻璃心，那就只好卖个萌了(✺ω✺)，哈哈哈
只是想搞清楚关系，没别的想法，希望您能继续维护下去，加油~

**Comment by sanggao** [comment]
哈哈哈哈或
