### ISSUE TITLE
最小差价设置

### ISSUE THREAD

**Issue by hongwanzhang** [sunoj/jjb#108]
希望增加最小差价设置功能，目前的差价选项0,1 0.5 1块感觉小了点，让用户自己设置会更好

**Comment by sunoj** [comment]
1块钱的差价可是单价哦，如果买了好几件还是很值得申请啊。
如果让用户直接输入，就需要做有效值校验，感觉不是特别有必要版？

**Comment by sunoj** [comment]
新版中增加了 5 元 的选项，这下应该够大了。

**Comment by hongwanzhang** [comment]
前几天看到并且设置了，非常感谢！
