### ISSUE TITLE
关于Firefox上的京价保

### ISSUE THREAD

**Issue by ryans233** [sunoj/jjb#11]
请问该版本的京价保是由作者本人移植还是授权移植？作为用户可否信任 hackplan 移植的版本？
京价保 - 京东价保助手 by hackplan https://addons.mozilla.org/en-US/firefox/addon/jjb/

**Comment by sunoj** [comment]
是我本人移植的，但是目前还有一些小的兼容问题

**Comment by ryans233** [comment]
了解。非常感谢作者移植到 Firefox，已捐款 5 元。
