### ISSUE TITLE
完成登录流程后不会重新检查PC登录状态

### ISSUE THREAD

**Issue by tjsky** [sunoj/jjb#110]
* 请详细的描述这个bug的细节

表现为：一直认为PC端未登录，完成登录流程后，也不会重新检查PC登录状态

* 你认为这个功能本应如何工作

可否增加一个手动强制检测登录状态按钮。
不然我都不知道是：
1. 虽然浏览器上JD登陆了，但是京价保的PC端用户名数据没获取到，认为未登录？
2. 虽然已经走了登录流程，但京价保没有触发自动检测登录，所以一直认为PC端未登录。

* 如果有可能，请提供截图
![截图](https://i.loli.net/2018/10/09/5bbc16c07826e.png)

 - OS: win7sp1
 - Browser Firefox60.2.2esr（64位）
 - Version 2.0.7

图片里，PC端检测登录状态提示是昨天21点多检测的。
其实我在昨天23点，今天7点，和刚提交前都重新登录过，但是京价保一直没跟新登录状态。

**Comment by sunoj** [comment]
已更新 2.0.8 解决
