### ISSUE TITLE
最近订单时间错误

### ISSUE THREAD

**Issue by linqiang007** [sunoj/jjb#111]
**Describe the bug**

如题,  前天，也就是这周二下的订单，显示上星期二

**Screenshots**

如果有可能，请提供截图

好像GitHub上传图片出问题了

**Desktop (please complete the following information):**
 - OS: macOs Mojave
 - Browser：Chrome Version 69.0.3497.100 (Official Build) (64-bit)
 - Version 2.0.7

你的操作系统、浏览器版本、京价保版本

**Comment by sunoj** [comment]
2.0.8 已经解决此问题
