### ISSUE TITLE
移动网页登录安全验证需要手势滑屏

### ISSUE THREAD

**Issue by opengit** [sunoj/jjb#112]
**移动网页登录安全验证需要手势滑屏**

在登录的时候，移动网页需要进行安全验证，需要滑屏，问，电脑端怎么滑屏？

<img width="420" alt="qq20181017-132401 2x" src="https://user-images.githubusercontent.com/12468408/47064033-4395ca80-d210-11e8-9c5c-8864bf879fb1.png">

**Comment by sunoj** [comment]
已经注意到此问题，马上会更新一版试图解决

**Comment by dududoor** [comment]
已经彻底无法登陆了，无论是箭头路线验证或是图标点选验证过后，都是反复提示“账号或密码不正确”，但是我可以确定账号密码没问题。

**Comment by sunoj** [comment]
> 已经彻底无法登陆了，无论是箭头路线验证或是图标点选验证过后，都是反复提示“账号或密码不正确”，但是我可以确定账号密码没问题。

收到个别反馈类似问题，但我尝试了多个账号未能重现，正在积极调查解决。

**Comment by sunoj** [comment]
> 已经彻底无法登陆了，无论是箭头路线验证或是图标点选验证过后，都是反复提示“账号或密码不正确”，但是我可以确定账号密码没问题。

能否禁用掉京价保，直接访问一下：https://wqs.jd.com/my/indexv2.shtml 然后登录试试，看是否是京价保的脚本影响。

**Comment by dududoor** [comment]
> > 已经彻底无法登陆了，无论是箭头路线验证或是图标点选验证过后，都是反复提示“账号或密码不正确”，但是我可以确定账号密码没问题。
> 
> 能否禁用掉京价保，直接访问一下：https://wqs.jd.com/my/indexv2.shtml 然后登录试试，看是否是京价保的脚本影响。
依然提示“账号或密码不正确”，在Chrome上登陆m.jd.com也是这个提示。
我在手机浏览器上登陆JD现在也是这个提示，APP和PC页面登陆都是正常的。
我得打950618找客户问一问了，可能是因为昨天反复登陆京价保（触发过一次账号密码错误多次请20分钟后登陆的提示），导致JD后台锁定了我登陆JD移动页面的权限。

**Comment by dududoor** [comment]
打客服电话他们给我发了一个重置码（8个字母数字混合码）让我改密码，改完以后再登陆移动页面依然提示“账号或密码不正确”……连着改了两次密码，都是如此，陷入死循环了。
在手机浏览器端可以跳转APP授权登陆，在电脑的Chrome上就只能用手机验证码的方式登陆JD移动页面了，目前勉强算是登上了京价保，它终于不再反复提示我了。

**Comment by sunoj** [comment]
> 打客服电话他们给我发了一个重置码（8个字母数字混合码）让我改密码，改完以后再登陆移动页面依然提示“账号或密码不正确”……连着改了两次密码，都是如此，陷入死循环了。
> 在手机浏览器端可以跳转APP授权登陆，在电脑的Chrome上就只能用手机验证码的方式登陆JD移动页面了，目前勉强算是登上了京价保，它终于不再反复提示我了。

京价保计划下一版在移动版未登录的情况下换用PC网页来价保，未来将逐步减少对移动版的依赖，现在移动端验证越来越复杂。另外下一版会引入一个每日自动登录次数配额的限制，防止京价保过多尝试登录。
