### ISSUE TITLE
麻烦隔离一下chrome和Firefox更新提醒

### ISSUE THREAD

**Issue by tjsky** [sunoj/jjb#114]
更新检测系统请不要给火狐用户推crx文件嘛

目前chrome有新版后，Firefox版也会收到提示。
我看代码里只是检测版本号小于服务器就提醒。

麻烦隔离一下不同版本插件/扩展的更新检测。
因为一般情况下，chrome和Firefox都不是同步更新的。
Firefox的慢，所以麻烦隔离一下更新提醒。
总给火狐用户推crx文件有点怪。

 - OS: win7 SP1
 - Browser firefox60.2.2ESR
 - Version 2.0.7

**Comment by sunoj** [comment]
有道理，是设计失误了。下一版改掉。

**Comment by sunoj** [comment]
已隔离
