### ISSUE TITLE
赞助10元，提个建议（以前的都关闭了不知道有人说过没）

### ISSUE THREAD

**Issue by gggccc44** [sunoj/jjb#115]
程序本身是表示不是一个免费应用但是免费提供使用，然而赞助了也无感啊，不能接入微信和支付宝？

我是用支付宝赞助的

如果麻烦或者支付宝微信会收取接入费用当我没说

个人觉得起码可以列出赞助名单

话说这次升级以后老是检测不到登录状态啊，是程序刷新的原因还是什么？而且登录时候没有jjb保存密码的菜单

**Comment by sunoj** [comment]
目前支付宝和微信均不允许个人接入，京价保暂时是一个个人作品。
赞助名单过长，无力人工更新。

登录时候没有京价保保存密码的选项说明京价保的脚本没有正常加载下来，观察一下如果不行建议卸载重装一下试试
