### ISSUE TITLE
登录时候没有保存密码的菜单

### ISSUE THREAD

**Issue by gggccc44** [sunoj/jjb#116]
自动更新到2.1.8的时候就出现了这个问题，然后好像很快又更新了2.1.9问题依旧，从新安装无法解决

测试了火狐和谷歌都有同样问题，也许是因为京东的原因？火狐测试了装旧版同样问题

![20181104](https://user-images.githubusercontent.com/1776304/47964981-d55c5f00-e07b-11e8-88cb-f8f27b398b93.jpg)

**Comment by sunoj** [comment]
登录页面的截图能截取一下吗

**Comment by gggccc44** [comment]
@sunoj 

如图
![01](https://user-images.githubusercontent.com/1776304/48053696-47e94e00-e1e6-11e8-8cbf-08e4f8f623ca.jpg)

![02](https://user-images.githubusercontent.com/1776304/48053702-4e77c580-e1e6-11e8-90de-54cf2903c5f5.jpg)

**Comment by gggccc44** [comment]
这几天jjb都没工作的样子，哪怕我手工登录

**Comment by sunoj** [comment]
这样看起来京价保的脚本没有成功的加载，这导致任何任务都是无法执行的。请提供一下浏览器的版本号

**Comment by sunoj** [comment]
如果有条件，可以在京东网页打开开发者工具，看能否看到“京价保注入页面成功” 和 “京价保开始执行任务”的字样

**Comment by gggccc44** [comment]
@sunoj 

console菜单里面？没有“京价保注入页面成功” 

谷歌内核55，360se浏览器
火狐是52ESR便携版

以前是正常的，我其实更怀疑是京东又改了什么，以前手机页面是不需要点图片验证的现在要点图片

**Comment by sunoj** [comment]
似乎这些版本都太老了。麻烦试一下新版的chrome，京东并没有修改任何页面导致京价保不可以，因为目前至少有上万人是正常使用京价保的。

**Comment by gggccc44** [comment]
@sunoj 

好的我试试，前几天还好好的
