### ISSUE TITLE
chrome 开启默认缩放后，布局不正常

### ISSUE THREAD

**Issue by Lunaticus7** [sunoj/jjb#117]
chrome 默认缩放调至 150% 时，插件布局错误，下半部和右侧元素显示不了
是限定了插件悬浮窗口尺寸的缘故？不太懂前端😀
![image](https://user-images.githubusercontent.com/2786456/48076358-fd84c300-e21f-11e8-9e8d-dc9321be0f39.png)
![image](https://user-images.githubusercontent.com/2786456/48076417-1b522800-e220-11e8-8383-2fe32bfd2fb1.png)

**Comment by sunoj** [comment]
感谢反馈，已更新 2.1.10 解决。
