### ISSUE TITLE
数据问题？

### ISSUE THREAD

**Issue by dmwin72015** [sunoj/jjb#118]
![image](https://user-images.githubusercontent.com/17537753/48745409-64858b80-eca6-11e8-8799-78ee50710252.png)

![image](https://user-images.githubusercontent.com/17537753/48745418-72d3a780-eca6-11e8-8dda-5911965429b2.png)

数据感觉不太对！

**Comment by sunoj** [comment]
京价保的价格数据不是全时段完整的，因为京价保并的价格数据来自用户，而不是爬虫。
