### ISSUE TITLE
对这个事怎么看？

### ISSUE THREAD

**Issue by gggccc44** [sunoj/jjb#119]
https://www.v2ex.com/t/511420

我本地没有复现，这种偷偷的和当初的各种劫持很类似啊，技术进步么。

其实我对返利并不排斥，jjb让我获得的价保已经超过了我的赞助（赞助过10元呵呵），我用的几个扩展都有申明广告链接，比如S3.Translator，有申明并且提供了关闭功能，但是我都默认打开，个人觉得京价保也可以做返利，申明就好了，反而脚本设置那里说的不是很清楚，要靠用户主动打赏是很困难的，扩展不是直播可以现场卖萌，而且感觉jjb不太可能做到移动端去

老外其实也不是真的素质高而是因为守规矩才能获益，我们还需要点时间，而且那确实给了我好感，至于说孩子糖尿病这种卖惨反而在天朝越来越没市场，好吧，我确实被影响到了，如果捐助简单的话我会给100rmb，不过这扩展好用是好用谷歌要翻墙。。。

再次感谢jjb，本来打了很多字结果蛋疼点了下github的链接都没了，感觉jjb做的很人性化一点不烦人，功能也实在

**Comment by sunoj** [comment]
感谢对京价保对喜欢和支持，最新版本的京价保增加了京东联盟引荐来源的展示和举报功能，协助大家来一起反劫持。

另，由于此问题不属于技术问题，先关闭了。
