### ISSUE TITLE
会跳到zaoshu.so这个网站

### ISSUE THREAD

**Issue by realchris007** [sunoj/jjb#120]
今天突然发现，从京价保的订单里，点开订单后会自动跳转到一个叫枣树集惠【https://jjb.zaoshu.so】的网站，然后再跳转到京东，然后chrome浏览器提示【已拦截不安全的内容，此网页试图从未经验证的来源加载脚本】，于是查了一下京价保的网站，在隐私说明，发现一句话：【京价保的主界面的活动推荐和网址推荐部分带有返利追踪，不点击即可】，难道这也是返利链接？？但为什么在【最近订单】里出现了？最后在它源代码的【显示引荐来源，优化界面更新】部分，找到了【zaoshu.so】这个网址，但我不是码农看不明白，希望大神看下这是做什么用的？

**Comment by sunoj** [comment]
在【高级设置】中打开 停用最近订单的链接 即可， 相关问题已经反复说明，不再详细解释。
