### ISSUE TITLE
金融会员无法签到

### ISSUE THREAD

**Issue by tankririri** [sunoj/jjb#121]
**Describe the bug**

请详细的描述这个bug的细节

金融会员无法签到

**To Reproduce**

Steps to reproduce the behavior

请详细描述重现这个bug的步骤

**Expected behavior**

你认为这个功能本应如何工作

**Screenshots**

如果有可能，请提供截图

**Desktop (please complete the following information):**

你的操作系统、浏览器版本、京价保版本
Windows 7 
chrome 71.0.3578.98
京价保2.2.1

**Additional context**

额外的描述

**Comment by onlyyy2014** [comment]
有同样的问题，好几天了

**Comment by backday0** [comment]
一样的问题

**Comment by sunoj** [comment]
这是因为京东金融去掉了网页版的签到，正在设法利用移动版实现。
