### ISSUE TITLE
开启剁手模式以后，同一个商品加入多数量到购物车，最终只有一件。

### ISSUE THREAD

**Issue by shanlanCoding** [sunoj/jjb#123]
复现方法：开启：“剁手模式”，随便找一件京东商品，然后把商品数量设置大于1，如设置为3件。加入购物车，此时会弹框出现“心灵拷问”模式，点击“坚持购买”，页面开始跳转，显示加购物车成功，数量为1.

如果关闭“剁手模式”，则恢复正常。

![k06a5 09 m_fx1d8kubf6m](https://user-images.githubusercontent.com/44717382/50812027-0abb4c80-134c-11e9-99c1-cb6320ae0d12.png)
![bf8jw d ruome2 go_ 0](https://user-images.githubusercontent.com/44717382/50812031-0d1da680-134c-11e9-89c3-e3f9c1a1a2fd.png)
![e _0hnh xa u1f vk 2tb](https://user-images.githubusercontent.com/44717382/50812047-13ac1e00-134c-11e9-989a-d1e689d40eb0.png)
![5o4s _jp6 q8 xt7v5os j3](https://user-images.githubusercontent.com/44717382/50812054-19a1ff00-134c-11e9-8356-402a4f144abc.png)

**Comment by sunoj** [comment]
感谢反馈，已修复
