### ISSUE TITLE
点击保价页面弹出的是PC端首页

### ISSUE THREAD

**Issue by tonybuaa** [sunoj/jjb#124]
**Describe the bug**

点击保价页面弹出的是PC端首页

**To Reproduce**

Steps to reproduce the behavior

点击保价页面

**Expected behavior**

以前会弹出特定的保价商品列表

**Screenshots**

![image](https://user-images.githubusercontent.com/1024698/51094745-86a11300-17ea-11e9-87d7-f41ffa450285.png)

**Desktop (please complete the following information):**

你的操作系统、浏览器版本、京价保版本
- Win7
- Chrome  71.0.3578.98
- Version 2.3.2

**Additional context**

额外的描述

**Comment by sunoj** [comment]
怀疑受到其他插件的影响

**Comment by sunoj** [comment]
直接打开：
https://msitepp-fm.jd.com/rest/priceprophone/priceProPhoneMenu
https://pcsitepp-fm.jd.com/rest/pricepro/priceapply

是否都可以正常打开价保页面呢

**Comment by lingjieqiu** [comment]
遇到了一样的问题

**Comment by littlezhanzhan** [comment]
> 直接打开：
> https://msitepp-fm.jd.com/rest/priceprophone/priceProPhoneMenu
> https://pcsitepp-fm.jd.com/rest/pricepro/priceapply
> 
> 是否都可以正常打开价保页面呢

打开这俩个网址也是京东首页

**Comment by fainboy** [comment]
打开 https://msitepp-fm.jd.com/rest/priceprophone/priceProPhoneMenu
是首页
打开 https://pcsitepp-fm.jd.com/rest/pricepro/priceapply
是保价页
