### ISSUE TITLE
京价保未考虑参加活动时价格，希望增加此价格

### ISSUE THREAD

**Issue by tjsky** [sunoj/jjb#127]
请详细填写以下四项关键元素

## 期待增加的功能描述
1、商品订单增加一个“实付款价格”项目。
2、价格曲线增加参加额外活动时的价格

## 实现此功能带来的增益：
价保申请会更加准确，价格曲线也更有参考价值

## 缺少此功能的影响
因为目前京价保对于类似 **买X件打N折** **跨店铺满X件减YY元** 的订单，显示的是商品原价，而不是打折后的价格。
所以很容易出现，商品降价了，但是比实际付款价格更贵时，依然申请价格保护。

## 实现的思路
1、价保时使用从订单页获取的商品实际成交价格。
2、价格曲线增加一个参与活动价格曲线

**Comment by golezi** [comment]
如果是要查看历史价格有更好的插件
价保感觉应该只看页面价格吧
比如说我30元买了一件东西
第二天页面价格不变，有活动第二件1元，相当于15.5一件了
这种情况个人感觉无法进行价保吧（实际上不清楚）

**Comment by tjsky** [comment]
@golezi 现在会造成一个问题，
比如我买东西时有活动满2件半价，页面每个商品300元，
我买了两个实际付款150元。
但是京价保的价保页面里，显示的商品价格是每个300元X2
第二天活动取消，商品价格变为每个200元
京价保就会认为商品从300降价为200去错误申请价保。

**Comment by sunoj** [comment]
已经在价格统计图中增加了促销活动信息
