### ISSUE TITLE
领券功能全部没用

### ISSUE THREAD

**Issue by willjean1** [sunoj/jjb#13]
包括精选优惠券，白条券。不是PLUS会员，PLUS券不清楚。手动刷新会提示已领到优惠券，点击提示会跳转到优惠券支持的商品页面，但实际上券并没有领到账户中来

Google Chrome 已是最新版本
版本 62.0.3202.94（正式版本） （64 位）

**Comment by sunoj** [comment]
京价保的领券只是点击了领券，实际有没有领到在京东。
