### ISSUE TITLE
京价保在mbp上会有字体发虚的显示异常

### ISSUE THREAD

**Issue by zeptolee** [sunoj/jjb#130]
**Describe the bug**

京价保在retina屏幕上可能会出现字体发虚的分辨率问题。

**To Reproduce**

我是两个屏幕共享，一个是retina屏，一个是普通屏幕，当把chrome拖拽到retina屏时，弹出的字体就会发虚，参见下方截图。

**Expected behavior**

保证分辨率正常显示

**Screenshots**

![image](https://user-images.githubusercontent.com/6327633/52929376-1e13fb80-337f-11e9-85e9-f45f7944e8a3.png)

**Desktop (please complete the following information):**
 - OS: 
![image](https://user-images.githubusercontent.com/6327633/52929391-371cac80-337f-11e9-8a00-e6c8c83b86f1.png)

![image](https://user-images.githubusercontent.com/6327633/52929407-46035f00-337f-11e9-835a-ad09543d904e.png)

![image](https://user-images.githubusercontent.com/6327633/52929420-50255d80-337f-11e9-91c9-58184341b982.png)

**Additional context**

**Comment by sunoj** [comment]
怀疑和系统有关，试试升级到 10.14.3
