### ISSUE TITLE
最近出现每天需要登录一次的问题

### ISSUE THREAD

**Issue by EngsShi** [sunoj/jjb#131]
只有近期才出现这个情况

**Comment by Beeta** [comment]
我也遇到了 每天都要登录好几次移动页面和电脑页面

**Comment by raofeng** [comment]
我这里是只要打开过电脑页面，过一会儿移动页面就需要重新登录。

**Comment by sunoj** [comment]
这是京东的策略决定的，当京东需要登录验证的时候，京价保无法自动完成登录。这不是京价保可以控制的。

**Comment by llity** [comment]
@sunoj 是否是因为京东检测到三方登录引起的？提示安全问题

**Comment by sunoj** [comment]
> @sunoj 是否是因为京东检测到三方登录引起的？提示安全问题

不能排除这个可能性，京东可能随时变更登录政策。
