### ISSUE TITLE
添加拓展开启/关闭开关功能

### ISSUE THREAD

**Issue by log2c** [sunoj/jjb#133]
## 原因
我在家里、公司的两台设备共用一个Chrome账号同步，由于公司要求等原因，我希望公司的电脑不要开启这拓展，而家里的电脑正常启用京价宝。
如果我通过Chrome设置禁用了京价宝拓展，则两台设备都会同步禁用，那么我每次回到家里，又要启用，到公司又要禁用。
如果添加开关功能，保存开关状态，则可以简单很多，希望作者考虑下，🙏谢谢。

**Comment by sunoj** [comment]
每一个任务都有关闭都选项，把所有的任务在公司的电脑关闭不就实现了吗？
