### ISSUE TITLE
书籍类价格保护的问题

### ISSUE THREAD

**Issue by monkey-sking** [sunoj/jjb#134]
请详细填写以下四项关键元素

## 期待增加的功能描述
书籍类商品取消触发价格保护
## 实现此功能带来的增益：
无
## 缺少此功能的影响
书籍类商品，在签收后就不能申请价格保护了，如果检测到是书签类物品能不能不触发价格保护？
## 实现的思路
无

**Comment by sunoj** [comment]
目前没有识别类目的能力，不过目前可以手动关闭价保（将鼠标移动到京价保“最近订单”中的订单左侧图片）
