### ISSUE TITLE
升级 Chrome 73 之后的问题

### ISSUE THREAD

**Issue by SHERlocked93** [sunoj/jjb#135]
在Chrome升级73之后，一直登陆都不成功了

![](https://i.loli.net/2019/03/17/5c8dc96e5bef5.png)

**Comment by sunoj** [comment]
点击登录有弹出登录页面吗？

**Comment by SHERlocked93** [comment]
> 点击登录有弹出登录页面吗？

是的，但是登陆之后，插件仍然显示要登陆，你可以升级chrome73试试，我觉得是安全方面的原因

**Comment by sunoj** [comment]
目前我也是73，我认为这并非chrome版本的原因，而是京东网页的差异导致的

**Comment by SHERlocked93** [comment]
> 目前我也是73，我认为这并非chrome版本的原因，而是京东网页的差异导致的

你 73 没有出现这样的情况么... 那这是什么情况哦 😅

**Comment by SHERlocked93** [comment]
刚刚试了一下，仍然是这样， emm

![](https://i.loli.net/2019/03/17/5c8dce758f32b.png)

**Comment by sunoj** [comment]
建议停用一下其他插件排除一下影响

**Comment by SHERlocked93** [comment]
> 建议停用一下其他插件排除一下影响

好的，我折腾一下看看

**Comment by SHERlocked93** [comment]
啊，我发现是我的锅，vpn开成全局的了... 🤪

sry~

**Comment by lhajh** [comment]
@sunoj 我的可以正常登录, 但是任务无法自动执行, 手动执行也没反应, 就提示 '正在重新运行xxx', 然后就没了

**Comment by lhajh** [comment]
开隐式模式就京价宝一个扩展也没反应

**Comment by sunoj** [comment]
> 开隐式模式就京价宝一个扩展也没反应

京价保无法在隐身模式下工作

**Comment by lhajh** [comment]
但正常模式也无法运行，无论自动还是手动

**Comment by sunoj** [comment]
> 但正常模式也无法运行，无论自动还是手动

请发邮件至 ming@tiny.group ，提供任务频率设置的截图，浏览器打开开发者工具并提供控制台截图，以便确认问题。

**Comment by lhajh** [comment]
找到原因了, 是由于 url render 这个插件引起的, 最近这个插件更新了
