### ISSUE TITLE
开了插件后，第二天访问jd会跳到joybuy.com也就是京东的国际站

### ISSUE THREAD

**Issue by nickfan** [sunoj/jjb#137]
请发送邮件至：ming@tiny.group
或在应用内“高级设置” - “建议反馈” 填写表单

京价保不设客服人员，可能不会回复你的咨询。

会通过链接跳转的时候跳转到 https://www.joybuy.com/?_cps=63167206.1210749820&utm_source=Aff38&utm_medium=affiliate&utm_campaign=48281_

之类的地址，需要人工重新访问jd.com才会回到国内站点。

![image](https://user-images.githubusercontent.com/100613/55998824-7b2e8c80-5cf2-11e9-955e-9b832cefd235.png)

**Comment by sunoj** [comment]
这和京价保没有关系，这很明显是被其他插件劫持了。
