### ISSUE TITLE
没有执行自动签到

### ISSUE THREAD

**Issue by weijhfly** [sunoj/jjb#138]
**Describe the bug**

任务设置是默认的，每天打开浏览器，京价保自动领了一堆plus券就没有下文了，签到要手动去点

**To Reproduce**

Steps to reproduce the behavior

无

**Expected behavior**

自动签到

**Screenshots**

无

**Desktop (please complete the following information):**

你的操作系统、浏览器版本、京价保版本
- OS: win7
 - Browser chrome 72.0.3626.81（正式版本） （64 位）
 - Version 2.4.3

**Additional context**

无

**Comment by sunoj** [comment]
建议先升级到 73

**Comment by weijhfly** [comment]
我看到差不多到12点后，自动签到完成了。还好，起码是自动的
