### ISSUE TITLE
插件隐藏到折叠菜单后点击无法显示完整界面

### ISSUE THREAD

**Issue by dickars** [sunoj/jjb#140]
插件隐藏到折叠菜单后点击无法显示完整界面，只能显示一半，如图：

![图片](https://user-images.githubusercontent.com/31948088/57591242-fccc4100-7562-11e9-9e92-8978e37e500d.png)

 - OS: Windows10 1809 (17763.168)
 - Browser Firefox 66.0.5 (x64)
 - Version 2.4.4

**Comment by sunoj** [comment]
这是Firefox的设定:

> If the user moves the extension's button to the menu or it appears in the toolbar overflow, then the popup appears inside the menu's panel and is given a fixed width.

参见：https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Popups
