### ISSUE TITLE
种豆得豆每2个小时自动收养料

### ISSUE THREAD

**Issue by Alexis374** [sunoj/jjb#141]
请详细填写以下四项关键元素

## 期待增加的功能描述
每日签到后有个种豆得豆的页面，每2/3个小时可以收货养分增加成长值，每周一根据上周的成长值瓜分京豆

**Comment by czmecho** [comment]
https://post.smzdm.com/p/aqndo2wk/

有好几个领京豆的入口，如果可以请增加。
