### ISSUE TITLE
手动执行某些项时，弹出层卡住

### ISSUE THREAD

**Issue by Teemwu** [sunoj/jjb#142]
**Describe the bug**

请详细的描述这个bug的细节

比如我手动执行“浏览店铺”这一项时，弹出提示，如图
![image](https://user-images.githubusercontent.com/16522288/58068164-caee5680-7bc2-11e9-9c77-3efb32862275.png)
点击“现在登陆”或者“知道了”都不会关闭，需要点击插件图标重新打开插件才能关闭。

**补充** 
- windows10
- chrome：74.0.3729.157
- 插件版本：2.5.1

**Comment by sunoj** [comment]
已更新 2.5.2 解决

**Comment by Teemwu** [comment]
弹出提示可以关闭了，但是登陆状态还是不对，“PC网页”和“移动网页”都登陆了，还是提示“糟糕，京东账号不在登陆状态”，无法手动执行“全品类券”等项。

**Comment by sunoj** [comment]
> 弹出提示可以关闭了，但是登陆状态还是不对，“PC网页”和“移动网页”都登陆了，还是提示“糟糕，京东账号不在登陆状态”，无法手动执行“全品类券”等项。

已更新 2.5.3， 现在应该没问题了？

**Comment by Teemwu** [comment]
可以正常执行了，给力:+1: @sunoj
