### ISSUE TITLE
最新消息打开看不见消息内容的情况

### ISSUE THREAD

**Issue by SHERlocked93** [sunoj/jjb#144]
版本：2.5.7
浏览器：chrome 74

![](https://i.loli.net/2019/05/24/5ce77dc28abe228485.png)

如图，最新消息打开之后没有内容

**Comment by sunoj** [comment]
感谢反馈 已更新 2.5.8 解决，请等待自动更新。

**Comment by SHERlocked93** [comment]
> 感谢反馈 已更新 2.5.8 解决，请等待自动更新。

赞👍，解决速度太快了～

**Comment by lim0513** [comment]
2.5.8 仍然存在此问题，提示有20个消息，一个看不到。。。

**Comment by sunoj** [comment]
> 2.5.8 仍然存在此问题，提示有20个消息，一个看不到。。。

等一等应用如果有新的消息出现应该就好了，当前的旧消息由于换了消息储存方案是显示不出来的。

**Comment by SHERlocked93** [comment]
> > 2.5.8 仍然存在此问题，提示有20个消息，一个看不到。。。
> 
> 等一等应用如果有新的消息出现应该就好了，当前的旧消息由于换了消息储存方案是显示不出来的。

emmm，似乎我更新了2.4.8之后还是看不到呀，mac上

**Comment by sunoj** [comment]
2.4.9 这次真的修好了，不过旧的消息显示不出来了，要等新消息。

**Comment by Itzamana** [comment]
> 2.5.9 这次真的修好了，不过旧的消息显示不出来了，要等新消息。

感谢~
