### ISSUE TITLE
能不能把app双签的金豆给加上

### ISSUE THREAD

**Issue by cairenbin** [sunoj/jjb#147]
请详细填写以下四项关键元素
## 期待增加的功能描述
能不能把app双签的金豆给加上
## 实现此功能带来的增益：
每天定时2豆,连签有增益,感觉还阔以
## 缺少此功能的影响
少了蚊子腿
## 实现的思路
观察了下好像两边APP都是挂载同一套H5进行签到的,不知道是否有可操作性
最后感谢小明对大家的无私奉献!

**Comment by sunoj** [comment]
实现不了，这个签到有限制，必须在客户端发起。

**Comment by cairenbin** [comment]
> 实现不了，这个签到有限制，必须在客户端发起。

谢谢!
