### ISSUE TITLE
Firefox版移动账户登录验证总是无法通过

### ISSUE THREAD

**Issue by Xiaochourentou** [sunoj/jjb#148]
Firefox版移动账户登录验证总是无法通过，点中了图案还是一样

**Comment by sunoj** [comment]
用 chrome 版呢？

**Comment by Xiaochourentou** [comment]
那倒是可以的

**Comment by Xiaochourentou** [comment]
2.6.4还是不行
![图片](https://user-images.githubusercontent.com/13693470/58958955-9db2c280-87d6-11e9-978a-c94378780eda.png)

**Comment by sunoj** [comment]
实验了一下，确实有问题，但是这个问题和京价保无关，禁用掉京价保以后，Firefox下仍然无法通过这个验证，怀疑是这个验证器在 Firefox 下面有兼容问题，看看京价保能否设法通过额外脚本解决。

**Comment by xqiushi** [comment]
我也有同样的问题，难道要放弃firefox了？

**Comment by YangFan1997** [comment]
同问，咋办捏，现在暂时的办法就是用QQ快速登录

**Comment by ChenXiyu** [comment]
同样的问题， Chrome 正常
FireFox 版本： 67.0.1
OS：MacOs 10.14.5
Plugin 版本： 2.6.4

**Comment by sunoj** [comment]
这是京东的验证码兼容问题，但是这个问题和京价保无关，禁用掉京价保以后，Firefox下仍然无法通过这个验证。

**Comment by mr-cn** [comment]
Firefox 67复现
出现验证码后，关掉页面，到PC端再登录即可登录。目前功能全部正常。
供参考

**Comment by fcying** [comment]
一样的问题.

**Comment by sunoj** [comment]
目前应该已经好了
