### ISSUE TITLE
建议添加抢plus券功能，20,40,50的太难抢了

### ISSUE THREAD

**Issue by vowers** [sunoj/jjb#150]
建议添加抢plus券功能，20,40,50的太难抢了，10元5元的自己随便点都可以，40 50 的每次守点都抢不到，

**Comment by sunoj** [comment]
因为这个券只有24小时的有效期，而总数又有限制，自动抢的话，以来不好控制频率和数量，二来时间不好预期，感觉做起来有难度

**Comment by vowers** [comment]
> 因为这个券只有24小时的有效期，而总数又有限制，自动抢的话，以来不好控制频率和数量，二来时间不好预期，感觉做起来有难度

其实可以做成手动添加，比如添加一次任务，今天抢一张2000减的卷，然后如果抢到的话就提示下，今天过了就取消，就设置成半自动那样，，

当然只是建议，确实可能需求不是很大
