### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by xhp281** [sunoj/jjb#151]
请详细填写以下四项关键元素

## 期待增加的功能描述
已完成订单批量好评

## 实现此功能带来的增益：
能领京豆

## 缺少此功能的影响
挨个评价太麻烦了

## 实现的思路
var content = '商品质量很好，很满意，配送速度快啊，而且配送员态度也非常好。';  
function a(){
var close=document.getElementsByClassName('btn-9 fail-close');
if(close.length>0){close[0].click()}
var assess=document.getElementsByClassName('btn-9')[0];
if(assess!=null){for(var i=0;i<2;i++){
assess.click();
var area=document.getElementsByClassName('area area01')[0];
area.value=content;area.setAttribute('id','id'+0);
$('#id'+0).blur();
var star=document.getElementsByClassName('star5')[0];star.click()}
var submit=document.getElementsByClassName('btn-5 mr10 setcomment')[0];
submit.click();
setTimeout('a()',5000)}};
a();

**Comment by sunoj** [comment]
请参考：https://github.com/sunoj/jjb/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E8%87%AA%E5%8A%A8%E8%AF%84%E4%BB%B7%E5%8A%9F%E8%83%BD%E4%B8%BA%E4%BB%80%E4%B9%88%E7%8E%B0%E5%9C%A8%E6%B2%A1%E6%9C%89%E4%BA%86
