### ISSUE TITLE
京东结算页面自动下单的问题

### ISSUE THREAD

**Issue by solorush** [sunoj/jjb#152]
**Describe the bug**
进入京东结算页面，还未来得及选收货地址等信息，就会自动下单。

**To Reproduce**

进入京东结算页面，还未来得及选收货地址等信息，就会自动下单，然后跳转到支付页面。每单必现，换电脑也必现。
查了下设置，没看到有相关功能。
关闭插件后，恢复正常。

**Expected behavior**

不该自动跳转，或者设置开关。

**Desktop (please complete the following information):**
 - OS: win10
 - Browser chrome 
 - Version 75
 - 插件版本 2.6.4

**Comment by sunoj** [comment]
京价保没有类似的功能，请复查是否是其他插件或脚本导致的
