### ISSUE TITLE
图形校验失败

### ISSUE THREAD

**Issue by 1312564541** [sunoj/jjb#155]
![图片](https://user-images.githubusercontent.com/26996878/60936755-cca1e400-a300-11e9-9bd2-dd11c7c70930.png)
明明已经点对了需要的图案，但是总是提示错误的，已经有一段时间了

**Comment by sunoj** [comment]
Firefox无法通过移动验证的问题此前已经解释，并且在Firefox插件页面介绍最上方做了说明。
