### ISSUE TITLE
历史价格数据中，是否能加入优惠后的最低价格？

### ISSUE THREAD

**Issue by dsjzazs** [sunoj/jjb#156]
比如一个商品原价100元，京东经常有满199减100的优惠券，按照这个优惠券计算后的参考价格为：(100/199)*100=50.251256元。

假如还有满2减5折可以同时存在的优惠，参考价格为：50.251256*0.5=25.125628元

要不然历史价格根本没啥参考意义嘛。

**Comment by sunoj** [comment]
这种折扣京价保是无法计算的，因为优惠券是限时限量的信息，而且需要凑其他商品来实现，属于非通用价格。如果要计算这种价格要引入很多数据，暂时不具备条件。
