### ISSUE TITLE
为什么在JD页面就会自动转跳个空白页面？ 

### ISSUE THREAD

**Issue by vicoho** [sunoj/jjb#157]
每每运行京价保的时候都会出现这个一个空白的标签，地址为http://cityadspix.com/blank-page。
有时候我手动打开JD的网页，他也直接自动转到那个地址，概率基本上就是每天的头几次。

**Comment by sunoj** [comment]
这个标签绝无可能是京价保创建的，请进一步调查。我在网上查出一些类似报告：http://bbs.huorong.cn/thread-50438-1-1.html
请复查是否被运营商或浏览器劫持

**Comment by vicoho** [comment]
> 这个标签绝无可能是京价保创建的，请进一步调查。我在网上查出一些类似报告：http://bbs.huorong.cn/thread-50438-1-1.html
> 请复查是否被运营商或浏览器劫持

3Q  看来是误会了， 我逐一排查试下
