### ISSUE TITLE
帐号登录问题

### ISSUE THREAD

**Issue by ff4c00** [sunoj/jjb#158]
![image](https://user-images.githubusercontent.com/28643773/62771032-db7de100-bace-11e9-8f0c-f7e1f36f4d73.png)
![image](https://user-images.githubusercontent.com/28643773/62771208-46c7b300-bacf-11e9-9504-3cd46d6c086e.png)
移动网页显示失败状态,点击现在登录,却显示的是登录后的用户页面

**Comment by golden1970** [comment]
点击，现在登录。
