### ISSUE TITLE
历史价格希望加入抓取促销信息部分

### ISSUE THREAD

**Issue by ywyha** [sunoj/jjb#161]
历史价格希望加入抓取促销信息部分，不需要计算，只需要记录展示就行 比如满2件，总价打8折；满3件，总价打7折

**Comment by sunoj** [comment]
很好的建议，已有计划增加

**Comment by ywyha** [comment]
> 很好的建议，已有计划增加

感谢大佬，希望可以增加指定商品商品价格变化，促销部分变化指定声音提醒，在本地完成也可以，最好在加个播报变化的商品名称 价格 与促销部分的朗读声音。

**Comment by sunoj** [comment]
2.6.5 已加上
