### ISSUE TITLE
希望增加商品自动评论的功能

### ISSUE THREAD

**Issue by hughcube** [sunoj/jjb#165]
希望增加商品自动评论的功能,   本身是一个薅羊毛的工具,    商品品论这块的得到的京豆可不少

**Comment by sunoj** [comment]
请参考：https://blog.jjb.im/faq.html

> 自动评价功能为什么现在没有了?
考虑到京东的评价对其他用户的重要参考性，以及一些商品评价晒单会有大额京豆返还，京价保取消了自动评价的功能，并且应该不会在未来重新加回来。
