### ISSUE TITLE
京价保不能拉取最新订单

### ISSUE THREAD

**Issue by gqk289** [sunoj/jjb#168]
现象：
安装京价保插件后，首次运行价格保护任务，可以拉到当前的订单列表，同时检查是否有价格保护的机会进行价格保护。但是，之后再通过京东下单的新订单，京价保无法拉取，即便是手动执行价格保护任务也不可以。除非删除京价保插件重新安装，可以拉到最新订单。
另外，虽然不能更新订单，但是安装插件的时候拉到的订单，后续仍会定期自动检查是否有价保机会。

版本信息：
macOS 10.14.6
京价保 2.6.5
Chrome 76.0.3809.132

**Comment by gqk289** [comment]
京东登录状态正常

**Comment by sunoj** [comment]
安装了多长时间？新订单下了之后过了多久没有拉取到？

**Comment by gqk289** [comment]
> 安装了多长时间？新订单下了之后过了多久没有拉取到
尝试安装过两次，第一次是大概两天后发现的，第二次是一天后发现的；订单下单十几个小时后仍未拉到，重装后立刻拉倒

**Comment by sunoj** [comment]
感谢反馈，会尽快调查解决，另外新版本中会增加一个运行日志来帮助更容易的了解运行状态

**Comment by gqk289** [comment]
感谢！

**Comment by gqk289** [comment]
会关注新版本，如果有日志会补充到这里

**Comment by gqk289** [comment]
同步一下，现在重新安装了最新版插件，暂时没有发现无法拉取最新订单的问题了，暂时 close 了
