### ISSUE TITLE
价保保护返还方式，可能是生鲜类特有的问题

### ISSUE THREAD

**Issue by huxuan** [sunoj/jjb#170]
请详细填写以下四项关键元素

## 期待增加的功能描述

生鲜类在价格保护时有两种返还方式的选项“限生鲜类京券”和“原返”，希望能提供价格保护并且返还方式为“原返”的功能

## 实现此功能带来的增益：

价格保护时实现原返，能够不折不扣要回差价

## 缺少此功能的影响

无良狗东默认是“限生鲜类京券”而且不支持修改默认设置，那样即使申请价保成功返还的也是带有效期的限品类券，是否能和其他优惠券叠加还有待验证

## 实现的思路

申请价保时的request有一个参数是`refundtype`，默认品类券的参数值是`2`，应该是只要强制设置为`1`就可以了

## 额外的话

感谢作者提供的京价保插件，帮助薅了不少羊毛，无奈前端写的少并且不熟悉chrome extension的开发，希望作者能帮助实现相应功能，如果愿意赐教，我也可以把这个当做练手task

**Comment by sunoj** [comment]
感谢反馈，非常有道理和有意义，下一版争取加上

**Comment by sunoj** [comment]
已在 2.7.2 增加
