### ISSUE TITLE
订单页面出现非自己的订单

### ISSUE THREAD

**Issue by BAQAQ** [sunoj/jjb#171]
请发送邮件至：ming@tiny.group
或在应用内“高级设置” - “建议反馈” 填写表单

京价保不设客服人员，可能不会回复你的咨询。
![image](https://user-images.githubusercontent.com/31987783/66270704-1ca13000-e889-11e9-9cf9-cc9edc38d7f6.png)

**Comment by BAQAQ** [comment]
不知道是哪里出了问题 可能是代码问题

**Comment by sunoj** [comment]
请点击左下角的“价保页面”对比订单，暂时没有收到类似反馈，我认为是个例

**Comment by BAQAQ** [comment]
价保页面进入我的京东是正常的，然后我发现早前的订单也有串的情况。主要是前两天登录过朋友的号，进入他的订单页面，我发现这些非自己的订单是他的订单，所以这是串号了？按理说每个账号应该能独立显示啊，那要是我谷歌浏览器登陆过好几个账号，都记住密码了的话，京价保会串号，可能是哪里有点问题，还望查查看 谢谢

**Comment by sunoj** [comment]
京价保不支持多账户使用，不存在“每个账户应该独立”这种功能。

**Comment by sunoj** [comment]
抱歉，无法针对这种个例进行调查。京价保默认你使用的是私人电脑。

**Comment by BAQAQ** [comment]
好的 那我去把账户数据清理下 谢谢
