### ISSUE TITLE
建议增加 签到领现金券

### ISSUE THREAD

**Issue by shawntao19** [sunoj/jjb#172]
请详细填写以下四项关键元素

## 期待增加的功能描述：
签到领现金券

## 实现此功能带来的增益：
随着签到次数可以自动领不同面值的现金券

## 缺少此功能的影响：
现金券什么时候都能用，有的时候比一些领到的优惠券还好用

## 实现的思路：
手机app-领券中心-签到领现金券-签到领券

**Comment by sunoj** [comment]
抱歉，京价保是一个 Chrome 插件，无法运行任何手机 App 上才能完成的操作
