### ISSUE TITLE
只有我安装插件的第一天在正常工作，后续就无任何作用了

### ISSUE THREAD

**Issue by rockingfire888** [sunoj/jjb#176]
第一天安装插件时还能有作用，从第二天开始就没任何作用了！！！！！
chrome浏览器，浏览器基本随时保持更新。
我的邮箱：raojp@qq.com

**Comment by ettwz** [comment]
一样的问题，mac10.14.6 chrome78.0.3904.97 京价保2.7.3

**Comment by sunoj** [comment]
能否点任务名称后面的“任务设置”图标然后看一下任务运行记录，看有没有运行

**Comment by ettwz** [comment]
![image](https://user-images.githubusercontent.com/20449556/70063363-96a02c00-1622-11ea-847e-4d0f63d3401c.png)
日志里有运行记录，券是可以正常领的，就是保价没反应

**Comment by sunoj** [comment]
看这个日志一切正常啊，点 + 展开一下日志呢。另外“保价没反应”具体是指什么表现？我看到有11月28号申请价保未通过的记录，这是手动申请的？

**Comment by ettwz** [comment]
![image](https://user-images.githubusercontent.com/20449556/70066341-8474bc80-1627-11ea-8d8e-ef840ebe18bd.png)
是我手动点了下面 `保价页面` 的按钮，手动同步来的。

**Comment by sunoj** [comment]
直接访问： https://pcsitepp-fm.jd.com/rest/pricepro/priceapply 能打开吗？如果打不开，那么：https://pcsitepp-fm.jd.com/ 能打开吗

**Comment by ettwz** [comment]
都可以打开，且正常登录
