### ISSUE TITLE
无法运行领券且无法获取最近订单

### ISSUE THREAD

**Issue by cold-snap** [sunoj/jjb#177]
**Describe the bug**

无法运行领券且无法获取最近订单

**Screenshots**

![image](https://user-images.githubusercontent.com/30111091/69052380-dfac8980-0a41-11ea-83ff-ac24490dc8e3.png)
![image](https://user-images.githubusercontent.com/30111091/69052426-f5ba4a00-0a41-11ea-9d6c-6d9b69581ca6.png)

**Desktop (please complete the following information):**

版本2.7.3
Chrome 79.0.3945.36
Windows 10 1903

**Comment by sunoj** [comment]
2.7.3 已经有任务运行记录了， 可以在任务设置中看一下

**Comment by 7inFen** [comment]
是的，最近很安静。也看不到订单记录。
