### ISSUE TITLE
未付款的订单也提起价保申请

### ISSUE THREAD

**Issue by benny856694** [sunoj/jjb#179]
**下单后未付款的订单也会提起价保申请**

请详细的描述这个bug的细节

**To Reproduce**

Steps to reproduce the behavior

请详细描述重现这个bug的步骤

**Expected behavior**

下单后未付款的订单不应该自动提起价保申请

**Screenshots**

如果有可能，请提供截图

**Desktop (please complete the following information):**

你的操作系统、浏览器版本、京价保版本

**Additional context**

额外的描述

**Comment by sunoj** [comment]
是的。
京价保根据京东价格保护列表提供的订单和商品执行检查，并不要求订单的状态。如果此现象困扰你，建议通过取消订单的方式来避免。
