### ISSUE TITLE
价格走势图横轴坐标显示错误

### ISSUE THREAD

**Issue by jinliming2** [sunoj/jjb#181]
**Describe the bug**

价格走势图横轴时间错误，30/60/90 天的图像貌似也有问题。

**To Reproduce**

打开一个详情页（比如 https://item.jd.com/100010133254.html ），查看价格走势图

**Expected behaviour**

横轴显示正确时间

**Screenshots**

![image](https://user-images.githubusercontent.com/10294977/71628489-2097e080-2c33-11ea-8bc3-b662d31c9912.png)

![image](https://user-images.githubusercontent.com/10294977/71628599-addb3500-2c33-11ea-9e0f-094fb46d9ab6.png)

![image](https://user-images.githubusercontent.com/10294977/71628652-ea0e9580-2c33-11ea-8a00-81975c2aee50.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - Browser: Chrome Canary
 - Version: 81

**Comment by sunoj** [comment]
看起来并无异常，横轴看起来和选择区间不一致是因为缺少数据

**Comment by sunoj** [comment]
确实有问题，最近部署的一套新的数据库返回的时间戳格式不太一样，导致有少数商品被存到新数据库的走势图时间是有误的，今天会修复。
