### ISSUE TITLE
移动端帐号失效但UI没有变化，依旧显示有效

### ISSUE THREAD

**Issue by mcoder2014** [sunoj/jjb#182]
请发送邮件至：ming@tiny.group
或在应用内“高级设置” - “建议反馈” 填写表单

京价保不设客服人员，可能不会回复你的咨询。

# 京东会员签到失效？
已经好几天没有成功签到京东会员了，可以看到有运行记录，但是上一次成功的时间是 12月25日，也就是有一周的时间了。

> 运行时间: 昨天 下午8:11+
运行时间: 昨天 下午6:40+
运行时间: 昨天 下午5:10+
运行时间: 昨天 下午3:40+
运行时间: 2019/12/31 下午7:19+
运行时间: 2019/12/31 下午5:49+
运行时间: 2019/12/31 下午4:17+
运行时间: 2019/12/31 下午2:47+
运行时间: 2019/12/30 下午6:16+
运行时间: 2019/12/30 下午4:46+
运行时间: 2019/12/30 下午3:16+

我看了下，似乎是移动端帐号已经失效了，但是UI上没有变化。
重新登录了移动端帐号，便可重新领券。

**Comment by sunoj** [comment]
此问题已经修复，等待chrome商店审核
