### ISSUE TITLE
不自动更新最近订单，我也不知道怎么手动更新最近订单

### ISSUE THREAD

**Issue by 2213238386** [sunoj/jjb#184]
不自动更新最近订单，我也不知道怎么手动更新最近订单

**Comment by sunoj** [comment]
点击右侧左下角“价保页面”按钮 等待页面加载完 然后看订单有没有抓到

**Comment by 2213238386** [comment]
可以了，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "sunoj"<notifications@github.com&gt;; 
发送时间: 2020年1月14日(星期二) 晚上6:32
收件人: "sunoj/jjb"<jjb@noreply.github.com&gt;; 
抄送: "满天星&amp;#x2728;"<2213238386@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [sunoj/jjb] 不自动更新最近订单，我也不知道怎么手动更新最近订单 (#184)




点击右侧左下角“价保页面”按钮 等待页面加载完 然后看订单有没有抓到
