### ISSUE TITLE
京价保卡死整个Chrome

### ISSUE THREAD

**Issue by vt-rli** [sunoj/jjb#190]
**Describe the bug**

最近两天，已经数次，频率约越数小时一次。
症状：CPU高占用，Chrome假死，Chrome Task Manager也停止刷新。
后来发现每次假死前Chrome Task Manager 刷新都停留在Subframe:jd.com有一个高占用率（cpu 会超过75%）

遂怀疑京价保，Task Manager结束此subframe后，恢复正常。
禁用插件后，再无卡死症状。

**To Reproduce**

Sorry，正在尝试寻找bug重现路径

**Expected behavior**

不应卡死。

**Screenshots**

-暂无-

**Desktop (please complete the following information):**
 
- OS: macOS 10.15.3
- Browser Chrome 80.0.3987.149 (Official Build) (64-bit)

**Additional context**

我将持续关注，如果再有线索会进一步提供给您，谢谢！

**Comment by sunoj** [comment]
怀疑是京东的前端代码的毛病，这个看起来是那个网页太卡了，之前出现过，我周末设法调查一下

**Comment by CenJing** [comment]
相同情况

**Comment by vt-rli** [comment]
过去几天一直没有启动『京价保』，未出现任何Chrome卡死。
今天升级了macOS后重启机器，用了2个小时左右又被卡死，无奈再次禁用 :(

**Comment by cairenbin** [comment]
是不是JD接口改过了，已经好几天没有成功操作纪录了，检查过登陆状态是正常的，同样伴有卡Chrome的现象，Win10 家庭版1909维持最新更新 Chrome80.0.3987.149 i7 9750h 24g内存的机器都卡。。。

**Comment by simon-ding** [comment]
same here

**Comment by leeshaoheng** [comment]
相同情况，win10 1909 edge dev

**Comment by CrytisMT** [comment]
same。。。

**Comment by sunoj** [comment]
有没有能提供一下浏览器的任务管理器截图的同学，我已经连续观察三天任务管理器了，还没遇到过cpu超过5%的情况

**Comment by leeshaoheng** [comment]
> 有没有能提供一下浏览器的任务管理器截图的同学，我已经连续观察三天任务管理器了，还没遇到过cpu超过5%的情况

我这边刚刚重装完浏览器，暂时没有出现这个问题了，我用一段时间看看

**Comment by cairenbin** [comment]
> 有没有能提供一下浏览器的任务管理器截图的同学，我已经连续观察三天任务管理器了，还没遇到过cpu超过5%的情况

我这边现在手段执行ok，没有再出现卡顿现象，但是看log，job都不运行了。。。哪里可以提取到执行log吗?

**Comment by freeleefly** [comment]
原来最近chrome总是卡住是是这个插件的原因呀。。。。

**Comment by simon-ding** [comment]
> 有没有能提供一下浏览器的任务管理器截图的同学，我已经连续观察三天任务管理器了，还没遇到过cpu超过5%的情况

<img width="451" alt="截屏2020-04-06 19 17 17" src="https://user-images.githubusercontent.com/9017681/78553187-733cf600-783b-11ea-99ab-9e3f93c7e878.png">

每次强制结束进程，chrome就不卡了

**Comment by sunoj** [comment]
已发行 2.8.0 由于京东现在提供了价保过期的标示，京价保现在按照这个标示，只检查还在价保期限的商品，大幅度减少了不必要的网络请求，请各位再观察一下，是否还有高占用问题。

**Comment by f1ume** [comment]
我也发现有这个情况，但只发生在beta版chrome。用正式版是没有，即使稳定版80->81，也没有。beta版80，81都会。是beta有特殊限制？留意到是在运行拍拍签到任务时cpu飙高，卡住
