### ISSUE TITLE
集成自动评论功能

### ISSUE THREAD

**Issue by wxthss82** [sunoj/jjb#191]
请详细填写以下四项关键元素

## 期待增加的功能描述：
自动填写购买后商品的评论

## 实现此功能带来的增益：
填写评论返京豆

## 缺少此功能的影响：
无

## 实现的思路：
我写过一个，参见：https://github.com/wxthss82/JD_AutoComment

**Comment by sunoj** [comment]
这个已经多次解释过：
考虑到京东的评价对其他用户的重要参考性，以及一些商品评价晒单会有大额京豆返还，京价保取消了自动评价的功能，并且应该不会在未来重新加回来。
