### ISSUE TITLE
登录异常！

### ISSUE THREAD

**Issue by webj1011** [sunoj/jjb#192]
昨天开始无法登陆账号，一直提示“加载异常，请重试”，试着从2.7.5更新到2.8.0，情况依旧。
ps：京东账号没问题，今天下午还在手机APP下了一单

**Comment by sunoj** [comment]
是京东登录页面提示加载异常吗？能否提供截图

**Comment by webj1011** [comment]
> 是京东登录页面提示加载异常吗？能否提供截图

折腾了半天，暂时不完美解决了，情况略复杂：
首先，问题源头应该是使用了“iGG谷歌访问助手”这个插件，就算关闭了它的连接功能（非禁用插件），也会导致京价保登陆出问题。重启浏览器跳出如下提示图，我才发现的；
![QQ截图20200417074728](https://user-images.githubusercontent.com/57495885/79518063-a9bc1180-8082-11ea-8d29-ffd6557e8e03.png)
然后，点恢复设置，京价保登录正常了，但没有结束；
接着，我作死又启用了访问助手，想再测试一遍，果然“顺利阵亡”，这次再按照上面的步骤操作一遍，却没“活”过来，这下苦逼了；
![QQ截图20200417074728](https://user-images.githubusercontent.com/57495885/79518441-ab3a0980-8083-11ea-92a1-a362cc1016ef.png)
![QQ截图20200417075206](https://user-images.githubusercontent.com/57495885/79518449-b0975400-8083-11ea-8ef1-d15e2104014d.png)
最后，终于发现QQ扫码还能顺利登陆。。。

总结一下，起因肯定是代理设置的问题，但是换一个思路，同样要登陆账号的“哔哩哔哩助手”一直没问题，京东网页版也一直能登陆，就京价保会掉，这是为啥？
再补充一点，选“短信验证登陆”，点“获取验证码”，也会跳出“加载异常”的提示。。。

**Comment by sunoj** [comment]
您提到的问题都跟京价保无关，京价保只是帮你打开京东的登录页面，京东的登录页面有风控机制，你用了代理导致触发了风控，这是京价保完全无法干预的。
