### ISSUE TITLE
领卷没有起作用

### ISSUE THREAD

**Issue by liuxyon** [sunoj/jjb#193]
请发送邮件至：ming@tiny.group
或在应用内“高级设置” - “建议反馈” 填写表单

京价保不设客服人员，可能不会回复你的咨询。

领券运行了一直没有显示任何领券结果, 并且登录京东也没有看到券增加. 需要什么特别设置么?

**Comment by sunoj** [comment]
具体指的哪一个领券任务？通知里面显示了券吗？

**Comment by snowdream** [comment]
感觉领券功能没起作用，除了一张充话费的优惠券之外，没有领到任何的全品券或者第三方优惠券。

**Comment by sunoj** [comment]
全品类券相当罕见，领不到很正常。第三方优惠券是之“PLUS专享券”这个任务吗？

**Comment by snowdream** [comment]
> 全品类券相当罕见，领不到很正常。第三方优惠券是之“PLUS专享券”这个任务吗？

看来东东抠门了。
我记得之前5元全品券到处dao'chu都是。

问题是第三方优惠券也没有自动领取。
能不能都领取了？万一后面用上了呢。😂

![image](https://user-images.githubusercontent.com/737958/80692707-8ffbdf00-8b04-11ea-815c-8abc78943388.png)
