### ISSUE TITLE
Bug：移动版登录无法拖动滑块

### ISSUE THREAD

**Issue by Editing42** [sunoj/jjb#198]
**Describe the bug**

移动版登录现在要求拖动滑块，但是操作时无法拖动

**To Reproduce**

移动版登录现在要求拖动滑块，但是操作时无法拖动

**Expected behavior**

可以正常拖动滑块

**Screenshots**

![image](https://user-images.githubusercontent.com/39005998/82974024-7ec2c700-a00b-11ea-9672-599721e55958.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser chrome83
 - Version 2.8.3

**Comment by sunoj** [comment]
是按住下方这个双箭头滑块拖动没有反应吗？

**Comment by Editing42** [comment]
是的

**Comment by sunoj** [comment]
> 是的

我这边测试遇到这种情况是可以拖动的，请问你在这个页面看到鼠标有没有变成小圆圈

**Comment by Editing42** [comment]
没有，还是箭头

**Comment by sunoj** [comment]
> 没有，还是箭头

这说明京价保引入的一个支持滑动的代码没有加载，你重新载入一下插件再尝试登录试试。

**Comment by Editing42** [comment]
ctrl+F5刷新后还是不行，看起来也没有报错
![image](https://user-images.githubusercontent.com/39005998/82978319-de729f80-a016-11ea-8015-dbe0e0b319d6.png)

**Comment by sunoj** [comment]
能否告知一下 Chrome 的具体版本，我今天在 Windows 上的 Chrome 81 测试也是正常的

**Comment by sunoj** [comment]
不好意思 看到你的版本了  chrome 83 我刚刚也试了一下 是ok的

**Comment by vadonmo** [comment]
我的刚刚也不可以。。。win10 2004 chrome 81

**Comment by vadonmo** [comment]
登陆网页版，然后突然可以了

**Comment by Editing42** [comment]
我的笔记本屏幕支持触摸，然后用屏幕能拖动，鼠标还是不行🌚

**Comment by xinyannp** [comment]
我也出现同样的问题，win10 1909 chrome 83

**Comment by sunoj** [comment]
> 我也出现同样的问题，win10 1909 chrome 83

我还是无法重现，怀疑和环境有关，能不能禁用掉其他所有插件单独运行京价保试一下能不能滑动。

**Comment by Editing42** [comment]
之前试过禁用其他插件，还是不行。现在在外面，等回去再试一下

**Comment by vadonmo** [comment]
> > 我也出现同样的问题，win10 1909 chrome 83
> 
> 我还是无法重现，怀疑和环境有关，能不能禁用掉其他所有插件单独运行京价保试一下能不能滑动。

![image](https://user-images.githubusercontent.com/8103489/83824456-1c538000-a709-11ea-9cd1-be0c8bbcb1c6.png)
我禁用了所有的插件，只留下这个，还是不行，这个是报错信息

**Comment by sunoj** [comment]
@vadonmo 你的设备不会也是有触摸支持的吧？我现在怀疑和设备本身的触摸支持有关

**Comment by vadonmo** [comment]
> @vadonmo 你的设备不会也是有触摸支持的吧？我现在怀疑和设备本身的触摸支持有关

没有，联想小新Pro 13，不带触摸屏。目前解决办法是切换到验证码登陆，收到短信后Ctrl+r刷新，然后自动登录就可以了，这一步就没有滑动出现了

**Comment by sunoj** [comment]
> > @vadonmo 你的设备不会也是有触摸支持的吧？我现在怀疑和设备本身的触摸支持有关
> 
> 没有，联想小新Pro 13，不带触摸屏。目前解决办法是切换到验证码登陆，收到短信后Ctrl+r刷新，然后自动登录就可以了，这一步就没有滑动出现了

`("ontouchstart" in window) || // touch events
               (window.Modernizr && window.Modernizr.touch) || // modernizr
               (navigator.msMaxTouchPoints || navigator.maxTouchPoints) > 2; `

你把这段代码复制到任意的Chrome窗口的 console 运行一下，结果是什么

**Comment by flatychen** [comment]
> > > @vadonmo 你的设备不会也是有触摸支持的吧？我现在怀疑和设备本身的触摸支持有关
> > 
> > 
> > 没有，联想小新Pro 13，不带触摸屏。目前解决办法是切换到验证码登陆，收到短信后Ctrl+r刷新，然后自动登录就可以了，这一步就没有滑动出现了
> 
> `("ontouchstart" in window) || // touch events (window.Modernizr && window.Modernizr.touch) || // modernizr (navigator.msMaxTouchPoints || navigator.maxTouchPoints) > 2; `
> 
> 你把这段代码复制到任意的Chrome窗口的 console 运行一下，结果是什么

我这边也有这个问题。这个似乎没法运行啊？

**Comment by sunoj** [comment]
> > > > @vadonmo 你的设备不会也是有触摸支持的吧？我现在怀疑和设备本身的触摸支持有关
> > > 
> > > 
> > > 没有，联想小新Pro 13，不带触摸屏。目前解决办法是切换到验证码登陆，收到短信后Ctrl+r刷新，然后自动登录就可以了，这一步就没有滑动出现了
> > 
> > 
> > `("ontouchstart" in window) || // touch events (window.Modernizr && window.Modernizr.touch) || // modernizr (navigator.msMaxTouchPoints || navigator.maxTouchPoints) > 2; `
> > 你把这段代码复制到任意的Chrome窗口的 console 运行一下，结果是什么
> 
> 我这边也有这个问题。这个似乎没法运行啊？

运行这个
`("ontouchstart" in window) ||  (window.Modernizr && window.Modernizr.touch) || (navigator.msMaxTouchPoints || navigator.maxTouchPoints) > 2;`

**Comment by vadonmo** [comment]
> > > > > @vadonmo 你的设备不会也是有触摸支持的吧？我现在怀疑和设备本身的触摸支持有关
> > > > 
> > > > 
> > > > 没有，联想小新Pro 13，不带触摸屏。目前解决办法是切换到验证码登陆，收到短信后Ctrl+r刷新，然后自动登录就可以了，这一步就没有滑动出现了
> > > 
> > > 
> > > `("ontouchstart" in window) || // touch events (window.Modernizr && window.Modernizr.touch) || // modernizr (navigator.msMaxTouchPoints || navigator.maxTouchPoints) > 2; `
> > > 你把这段代码复制到任意的Chrome窗口的 console 运行一下，结果是什么
> > 
> > 
> > 我这边也有这个问题。这个似乎没法运行啊？
> 
> 运行这个
> `("ontouchstart" in window) || (window.Modernizr && window.Modernizr.touch) || (navigator.msMaxTouchPoints || navigator.maxTouchPoints) > 2;`

true

**Comment by sunoj** [comment]
果然！这个条件是京价保的模拟触摸的脚本判断设备本身有没有触摸功能的，这个脚本如果是true的话，就不运行这个模拟触摸事件的脚本了。

麻烦分别运行一下：
`("ontouchstart" in window) `

`(window.Modernizr && window.Modernizr.touch) `

` (navigator.msMaxTouchPoints || navigator.maxTouchPoints) > 2;`

看看具体情况吧

**Comment by vadonmo** [comment]
> 果然！这个条件是京价保的模拟触摸的脚本判断设备本身有没有触摸功能的，这个脚本如果是true的话，就不运行这个模拟触摸事件的脚本了。
> 
> 麻烦分别运行一下：
> `("ontouchstart" in window) `
> 
> `(window.Modernizr && window.Modernizr.touch) `
> 
> ` (navigator.msMaxTouchPoints || navigator.maxTouchPoints) > 2;`
> 
> 看看具体情况吧

false undefined true，最后一个的锅

**Comment by sunoj** [comment]
> > 果然！这个条件是京价保的模拟触摸的脚本判断设备本身有没有触摸功能的，这个脚本如果是true的话，就不运行这个模拟触摸事件的脚本了。
> > 麻烦分别运行一下：
> > `("ontouchstart" in window) `
> > `(window.Modernizr && window.Modernizr.touch) `
> > ` (navigator.msMaxTouchPoints || navigator.maxTouchPoints) > 2;`
> > 看看具体情况吧
> 
> false undefined true，最后一个的锅，navigator.maxTouchPoints是20

https://patrickhlauke.github.io/touch/touchscreen-detection/ 访问一下这个网页，看这个判断好不好，如果这个判断好的话，我换个判断就行了

**Comment by vadonmo** [comment]
> > > 果然！这个条件是京价保的模拟触摸的脚本判断设备本身有没有触摸功能的，这个脚本如果是true的话，就不运行这个模拟触摸事件的脚本了。
> > > 麻烦分别运行一下：
> > > `("ontouchstart" in window) `
> > > `(window.Modernizr && window.Modernizr.touch) `
> > > ` (navigator.msMaxTouchPoints || navigator.maxTouchPoints) > 2;`
> > > 看看具体情况吧
> > 
> > 
> > false undefined true，最后一个的锅，navigator.maxTouchPoints是20
> 
> https://patrickhlauke.github.io/touch/touchscreen-detection/ 访问一下这个网页，看这个判断好不好，如果这个判断好的话，我换个判断就行了

![image](https://user-images.githubusercontent.com/8103489/84125479-307fe000-aa6f-11ea-81b0-828ab103904b.png)

**Comment by sunoj** [comment]
> > > > 果然！这个条件是京价保的模拟触摸的脚本判断设备本身有没有触摸功能的，这个脚本如果是true的话，就不运行这个模拟触摸事件的脚本了。
> > > > 麻烦分别运行一下：
> > > > `("ontouchstart" in window) `
> > > > `(window.Modernizr && window.Modernizr.touch) `
> > > > ` (navigator.msMaxTouchPoints || navigator.maxTouchPoints) > 2;`
> > > > 看看具体情况吧
> > > 
> > > 
> > > false undefined true，最后一个的锅，navigator.maxTouchPoints是20
> > 
> > 
> > https://patrickhlauke.github.io/touch/touchscreen-detection/ 访问一下这个网页，看这个判断好不好，如果这个判断好的话，我换个判断就行了
> 
> ![image](https://user-images.githubusercontent.com/8103489/84125479-307fe000-aa6f-11ea-81b0-828ab103904b.png)

额。。。
没事，我把判断里面的这个 (navigator.msMaxTouchPoints || navigator.maxTouchPoints) > 2; 去掉得了

**Comment by flatychen** [comment]
> > > > > @vadonmo 你的设备不会也是有触摸支持的吧？我现在怀疑和设备本身的触摸支持有关
> > > > 
> > > > 
> > > > 没有，联想小新Pro 13，不带触摸屏。目前解决办法是切换到验证码登陆，收到短信后Ctrl+r刷新，然后自动登录就可以了，这一步就没有滑动出现了
> > > 
> > > 
> > > `("ontouchstart" in window) || // touch events (window.Modernizr && window.Modernizr.touch) || // modernizr (navigator.msMaxTouchPoints || navigator.maxTouchPoints) > 2; `
> > > 你把这段代码复制到任意的Chrome窗口的 console 运行一下，结果是什么
> > 
> > 
> > 我这边也有这个问题。这个似乎没法运行啊？
> 
> 运行这个
> `("ontouchstart" in window) || (window.Modernizr && window.Modernizr.touch) || (navigator.msMaxTouchPoints || navigator.maxTouchPoints) > 2;`

我的的确是带触摸屏了，但我一直禁用了。返回的是ture

**Comment by vadonmo** [comment]
> @flatychen @vadonmo @Editing42 麻烦各位帮忙试一下，访问这个网页，触摸模拟是否正常工作：https://vigilant-curran-f4d0b5.netlify.app
> 
> 如果正常工作的话，在京东移动版登录网页，开发者工具控制台粘贴运行下面的代码，能否让鼠标可以滑动：
> 
> `function injectScript(file, node) { var th = document.getElementsByTagName(node)[0]; var s = document.createElement('script'); s.setAttribute('type', 'text/javascript'); s.setAttribute('charset', "UTF-8"); s.setAttribute('src', file); th.appendChild(s); }; injectScript("https://vigilant-curran-f4d0b5.netlify.app/touch-emulator.js", 'body'); setTimeout(function () { console.log('TouchEmulator'); TouchEmulator(); }, 1200);`

这个没问题，能够正常触摸滑动

**Comment by sunoj** [comment]
已经更新2.8.5解决部分设备上的滑动问题，请各位观察一下

**Comment by Editing42** [comment]
我这里可以工作了，感谢开发者修复

**Comment by mattxubin** [comment]
Firefox 目前JJB的版本是2.8.3，也有这个问题。请问也会更新吗？

**Comment by sunoj** [comment]
> Firefox 目前JJB的版本是2.8.3，也有这个问题。请问也会更新吗？

已经提交审核了，等更新
