### ISSUE TITLE
怎么取消很多店铺的券啊？每天领了几十张券。。。 只想保留全品类券和白条券。

### ISSUE THREAD

**Issue by yhwhu** [sunoj/jjb#199]
请发送邮件至：ming@tiny.group
或在应用内“高级设置” - “建议反馈” 填写表单

京价保不设客服人员，可能不会回复你的咨询。

**Comment by sunoj** [comment]
关闭PLUS专享券 这个任务就好了

**Comment by yhwhu** [comment]
> 关闭PLUS专享券 这个任务就好了

好的，非常感谢！
