### ISSUE TITLE
Firefox 版本

### ISSUE THREAD

**Issue by CzBiX** [sunoj/jjb#2]
Firefox 已经切换到 WebExtensions 的扩展实现机制，Chrome 扩展迁移到 Firefox 会比较方便。
不知是否有意向移植及维护 Firefox 版本？

**Comment by sunoj** [comment]
本人日常并不使用Firefox，因此可能无力维护一个Firefox版，若有兴趣可自行移植，但是仅限个人使用，请勿上传到Firefox插件市场。
