### ISSUE TITLE
历史价格接口控制台报错

### ISSUE THREAD

**Issue by Tongzzzzz** [sunoj/jjb#201]
历史价格接口报错如下:

![image](https://user-images.githubusercontent.com/26567782/84681215-625cdf00-af66-11ea-91d5-cff01911e4ea.png)

直接调用接口不添加day参数可以返回结果, 

![image](https://user-images.githubusercontent.com/26567782/84681471-bebffe80-af66-11ea-8790-23f4f2edba55.png)

添加day参数浏览器报错
![image](https://user-images.githubusercontent.com/26567782/84681360-9506d780-af66-11ea-9db4-45639eb7702c.png)

**Comment by sunoj** [comment]
已解决，是腾讯云的cdn出了点问题
