### ISSUE TITLE
建议修改自动登录为可选项

### ISSUE THREAD

**Issue by ifconf** [sunoj/jjb#203]
请详细填写以下四项关键元素

## 期待增加的功能描述：
 可选自动登录或手动登录功能，增加退出登录功能；

## 实现此功能带来的增益：
 将手动登录/退出登录的选择交给用户；

## 缺少此功能的影响：
保存密码之后似乎都会自动登录，有时候会登录失败（需要手动滑动验证码），自动登录失败会有chrome通知，正在做其他事情的时候可能不太想重新登录，这时候如果可以将自动登录设置为手动登录或者暂时退出登录会好一点。

**Comment by sunoj** [comment]
这个问题近期确实会设法解决，会退出一个静默模式，登录掉线的时候也不会提醒
