### ISSUE TITLE
最近两天总是提示登录，登录无线版一天要登录十几次，这是怎么了？

### ISSUE THREAD

**Issue by bbfxier** [sunoj/jjb#207]
是因为我的账号的原因吗？
还是因为京东升级策略了？

**Comment by sunoj** [comment]
是京东的策略变化

本周更新 2.8.6 主要为移动版登录失效的提醒增加了一个“不再提醒”的选项，点击“不再提醒”后，移动版登录失效将不再发送浏览器通知。

由于移动版登录的有效期进一步降低，可能之后还需要进一步设法降低影响，甚至移除掉对移动版登录的依赖。
