### ISSUE TITLE
界面显示有问题

### ISSUE THREAD

**Issue by zl939144892** [sunoj/jjb#216]
**Describe the bug**
界面显示有问题

**Screenshots**
![image](https://user-images.githubusercontent.com/18364560/96945655-ec1e4980-1510-11eb-9196-7b3e53f5ad1c.png)

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [chrome]
 - Version [2.9.0]

你的操作系统、浏览器版本、京价保版本

**Additional context**

额外的描述

**Comment by sunoj** [comment]
确实在新版里面为了支持独立窗口的模式改动了布局方式，但是我这边测试在 Mac 版的 Chrome 上没有问题，你的 Chrome 版本是？

**Comment by zl939144892** [comment]
这个属性的问题
![image](https://user-images.githubusercontent.com/18364560/96954105-4c1eeb00-1525-11eb-9cfd-e7ea93a68cbe.png)

**Comment by zl939144892** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/18364560/96954276-a324c000-1525-11eb-9526-d1ffcdd52776.gif)

**Comment by sunoj** [comment]
确实是这个样式的影响，但是这个样式是设计中的，在界面较窄的模式下，隐藏掉设置，这是符合设计的。
当你遇到的效果确实不符合预期，我这边的并未重现这样的问题。

<img width="1109" alt="Screen Shot 2020-10-23 at 12 02 15 PM" src="https://user-images.githubusercontent.com/1835150/96955194-9d2fde80-1527-11eb-8330-6ae2118ba4ae.png">

目前需要排除一下差异，方不方便新开一个浏览器用户在没有其他插件的情况下单独安装一下京价保

**Comment by sunoj** [comment]
是不是在 Chrome 的设置里面设置了 Page zoom ？

**Comment by zl939144892** [comment]
![image](https://user-images.githubusercontent.com/18364560/97125928-64367a80-1770-11eb-8d5e-191550166809.png)

**Comment by sunoj** [comment]
新版本 2.9.1 已解决该问题

**Comment by zl939144892** [comment]
👍
