### ISSUE TITLE
京东报价页面显示 抱歉，系统繁忙请您稍后重试！

### ISSUE THREAD

**Issue by ferdiina** [sunoj/jjb#217]
https://pcsitepp-fm.jd.com/
价格保护申请 Tab
总是提示  抱歉，系统繁忙请您稍后重试！
关闭插件后解决

**Comment by sunoj** [comment]
插件版本是多少？

**Comment by ferdiina** [comment]
2.9.1

**Comment by sunoj** [comment]
能否提供一个报错截图呢，这个问题目前没有收到类似反馈，我本人也无法重现

**Comment by ferdiina** [comment]
![image](https://user-images.githubusercontent.com/26917117/97397967-5bd37080-1925-11eb-8142-413d394660b7.png)
开启插件后显示，并且价格保护会自动运行
关闭插件后
![image](https://user-images.githubusercontent.com/26917117/97398116-989f6780-1925-11eb-8c8e-0802c08eafa1.png)

**Comment by sunoj** [comment]
大概调查出一个问题了 争取今天稍晚时候更新解决

**Comment by ferdiina** [comment]
厉害！
