### ISSUE TITLE
安装的最新版本 咋拉取不到我的订单列表了 都是最新的订单(昨天 前天都有订单)

### ISSUE THREAD

**Issue by ran1ever** [sunoj/jjb#220]
请发送邮件至：ming@tiny.group
或在应用内“高级设置” - “建议反馈” 填写表单

京价保不设客服人员，可能不会回复你的咨询。

**Comment by sunoj** [comment]
"最新版本"是什么版本号？

**Comment by ran1ever** [comment]
![QQ截图20201030160212.png](https://i.loli.net/2020/10/30/lywj5MivIOCa3kD.png)

**Comment by sunoj** [comment]
请知悉，这个版本并非最新版，请使用 Chrome 商店 安装最新版 2.9.3

**Comment by ran1ever** [comment]
感谢 此版本是从 jjb.im 上装的   我去换成最新的

**Comment by ran1ever** [comment]
安装了 2.9.3 还是没有订单数据 看了下 Chrome 商店 插件下的评论 有位老哥也是和我一样的情况
https://i.loli.net/2020/10/30/snKmWpC6I12Q7Gy.png

**Comment by sunoj** [comment]
请耐心等一会儿 等价保运行 或者手动点击一下弹出窗口下方的“价保页面”
