### ISSUE TITLE
这插件现在还有用吗?

### ISSUE THREAD

**Issue by wangxufire** [sunoj/jjb#224]
很久没自动价保了

**Comment by raybi-asus** [comment]
今天还在自动价保

**Comment by wangxufire** [comment]
> 今天还在自动价保

能试试edge浏览器行不行吗

**Comment by sunoj** [comment]
> > 今天还在自动价保
> 
> 能试试edge浏览器行不行吗

具体不行是插件不能运行，还是插件运行了但是没有获取到订单，还是获取到订单了但是没有发现降价，还是发现了降价没有提交申请，还是提交了申请没有成功？
请提供一些信息量来获取帮助，不要做完全无信息量的反馈，这样的反馈不能帮到自己也不能帮到别人。

**Comment by wangxufire** [comment]
> > > 今天还在自动价保
> > 
> > 
> > 能试试edge浏览器行不行吗
> 
> 具体不行是插件不能运行，还是插件运行了但是没有获取到订单，还是获取到订单了但是没有发现降价，还是发现了降价没有提交申请，还是提交了申请没有成功？
> 请提供一些信息量来获取帮助，不要做完全无信息量的反馈，这样的反馈不能帮到自己也不能帮到别人。

有订单 没有价保记录 即使手动运行价保 价保记录也是不会产生记录

**Comment by wangxufire** [comment]
即使是未发生降价yi qm

**Comment by sunoj** [comment]
> 即使是未发生降价以前也会产生记录的吧,现在成功失败价保记录都没有记录,是空的

现在这个反馈变得非常有价值，因为你提供了详细的情况和具体的问题。
但是我感到有些奇怪：为什么期待没有降价也会产生价保记录？

成功的价保没有记录确实是不应该的，请直接访问：https://pcsitepp-fm.jd.com/rest/pricepro/priceapply  看能否看到成功的价保记录

**Comment by wangxufire** [comment]
> > 即使是未发生降价以前也会产生记录的吧,现在成功失败价保记录都没有记录,是空的
> 
> 现在这个反馈变得非常有价值，因为你提供了详细的情况和具体的问题。
> 但是我感到有些奇怪：为什么期待没有降价也会产生价保记录？
> 
> 成功的价保没有记录确实是不应该的，请直接访问：https://pcsitepp-fm.jd.com/rest/pricepro/priceapply 看能否看到成功的价保记录

没成功的有记录可以知道运行过了,而且以前就一直有的,很遗憾未发生降价..不是要提新需求.这个链接是有记录的

**Comment by sunoj** [comment]
> > > 即使是未发生降价以前也会产生记录的吧,现在成功失败价保记录都没有记录,是空的
> > 
> > 
> > 现在这个反馈变得非常有价值，因为你提供了详细的情况和具体的问题。
> > 但是我感到有些奇怪：为什么期待没有降价也会产生价保记录？
> > 成功的价保没有记录确实是不应该的，请直接访问：https://pcsitepp-fm.jd.com/rest/pricepro/priceapply 看能否看到成功的价保记录
> 
> 没成功的有记录可以知道运行过了,而且以前就一直有的,很遗憾未发生降价..不是要提新需求.这个链接是有记录的

所以并非你之前提到的：“即使是未发生降价以前也会产生记录的吧”，而是报告现在缺少“（发现降价并申请了）没成功的有记录”

**Comment by sunoj** [comment]
这个报告包含不清晰的表达和混乱的描述，可能带给其他人误导性，先关闭掉。
如需继续报告问题，请按照 issue 模版，准确、清晰、完整的提供问题报告。
