### ISSUE TITLE
京价宝登录京东遇到超难验证码造成无法登录

### ISSUE THREAD

**Issue by quqixun** [sunoj/jjb#228]
浏览器： Chrome 88.0.4324.96
京价宝：2.9.4

使用京价宝登录京东遇到如下超难验证码
![image](https://user-images.githubusercontent.com/3949332/106404844-13b97200-646f-11eb-93ec-7319e3d384ec.png)

这是不是被针对了？

**Comment by dbccaij** [comment]
我也遇到超难验证码
