### ISSUE TITLE
最近好几天没有自动运行了。

### ISSUE THREAD

**Issue by mTerminal** [sunoj/jjb#24]
发现登录京东的时候需要输入验证码了，不知道是不是这个原因，已经好几天不能自动领券和签到了。

**Comment by sunoj** [comment]
是不是开了VPN？需要验证码肯定是没办法自动登录的

**Comment by mTerminal** [comment]
@sunoj 电脑上一直挂的 ss,京东是走国内直连的，用了半个月没事，就是前几天开始的。
