### ISSUE TITLE
无法自动启动任务

### ISSUE THREAD

**Issue by shunia** [sunoj/jjb#25]
如果不手动刷新,任务不会自动启动.

截图是我今天打开chrome超过2个小时之后:
![image](https://user-images.githubusercontent.com/779430/34285129-334f1f44-e712-11e7-9133-e5047605bc08.png)

**Comment by leemessi** [comment]
me too

**Comment by willie91** [comment]
+1，好像是更新了这个版本之后出现的问题，上个版本没问题。

**Comment by sunoj** [comment]
已经确认问题，预计今天更新修复

**Comment by sunoj** [comment]
问题已解决，并做了一次大幅的更新，增加了消息模块， 等待自动更新，或者去拓展管理页面手动更新一下吧。
