### ISSUE TITLE
有没有可能增加一个京东金融里面每日打卡的功能？

### ISSUE THREAD

**Issue by qinruimac** [sunoj/jjb#26]
京东金融里面有个每日充值1元，次日8:00前打卡瓜分的游戏。有没有可能把这个做成自动的？

**Comment by sunoj** [comment]
不能，据我所致这是必须在App端操作的，而京价保是一个 chrome 插件。
并且每日打卡的规则也不支持用程序化的方法去打卡，并且我认为对于其他参与此游戏的人，这是在作弊。
