### ISSUE TITLE
希望能够增加自动评论功能

### ISSUE THREAD

**Issue by tianmaozhi** [sunoj/jjb#28]
希望能够增加自动评论功能

**Comment by vmvz** [comment]
现在还是无法自动选择 标签, 还是半自动评价
![image](https://user-images.githubusercontent.com/1652700/35133869-a770c538-fd0d-11e7-82d3-58265fdac163.png)

**Comment by sunoj** [comment]
是的，目前这个功能还未完成，默认是关闭的

**Comment by dsky1990** [comment]
+1，这个功能很实用

**Comment by chenenze** [comment]
+1，这个功能很实用

**Comment by itsjoke** [comment]
+1，这个功能很实用

**Comment by stnaw** [comment]
+1，这个功能很实用
