### ISSUE TITLE
新版本的chrome崩溃到不行

### ISSUE THREAD

**Issue by FindHao** [sunoj/jjb#29]
chrome63，我看评论里62也崩溃。

**Comment by FindHao** [comment]
os: Debian 9 X64

**Comment by sunoj** [comment]
Debian 以及 类UNIX系统下面均未经测试，大部分反馈崩溃问题都是此类系统。 建议自行调查崩溃原因，或卸载本插件。

**Comment by FindHao** [comment]
@sunoj 新版本的firefox下也不能正常运行。看来是linux的问题？
