### ISSUE TITLE
时间一长Chrome自动关闭

### ISSUE THREAD

**Issue by CuminLo** [sunoj/jjb#30]
系统 Arch Linux
Chrome 版本 63.0.3239.132（正式版本） （64 位）

只要一打开插件，时间一长（并没准备计算，有时候半小时 有时候几个小时） Chrome就会没有反应，然后自动关闭。

禁用插件之后就一切正常

**Comment by CuminLo** [comment]
所以我现在每天都是签到之后，就关闭插件，第二天再打开....

**Comment by sunoj** [comment]
Linux 系统目前发现有明显的问题，但目前暂时无力支持，需要自行调研，欢迎开PR
