### ISSUE TITLE
希望能加入对QQ浏览器的支持

### ISSUE THREAD

**Issue by iamsweet** [sunoj/jjb#31]
在QQ浏览器上无效果，F12能看到报错
extension://gfgkebiommjpiaomalcbfefimhhanlfd/static/content_script.js:27 Uncaught SyntaxError: Unexpected token function
国产浏览器用户群挺大的，希望能支持

**Comment by sunoj** [comment]
http://bbs.browser.qq.com/thread-236894-1-1.html 你用beta版试试呢？

**Comment by iamsweet** [comment]
非常感谢，beta版是正常的~
