### ISSUE TITLE
能否增加手动/自动申请开关？

### ISSUE THREAD

**Issue by shimingyu5** [sunoj/jjb#32]
能否增加一个选择手动/自动申请的开关？在发现可以价保等机会时可以选择自动申请或者提示可以申请，由用户手动申请价保。

**Comment by sunoj** [comment]
那么这个提示的有效期有多长呢，如果用户没有点击是否要回收提示呢？如果价格二次变动是不是也需要回收提示呢？如果在深夜电脑休眠的时候发现价保机会是否要自动完成呢？

**Comment by shimingyu5** [comment]
选择手动提示就相当于放弃自动申请的机会，由使用者进行选择，如果需要保证时效就用自动模式，已经发出的提示就类似于历史消息，只保证发出时有效，不保证时效性，每次运行时发现机会均可报警。

**Comment by sunoj** [comment]
建议自己修改代码实现，如果愿意放弃版权也可以贡献代码发MR。
