### ISSUE TITLE
登陆后还提示登陆

### ISSUE THREAD

**Issue by dsky1990** [sunoj/jjb#33]
<img width="671" alt="2018-01-23 5 01 04" src="https://user-images.githubusercontent.com/1579516/35266677-ed519128-005e-11e8-8983-29e02fbc9059.png">

**Comment by sunoj** [comment]
请具体描述情况

**Comment by dsky1990** [comment]
上图中，点击登陆京东后，登陆完成，但是再次点击拓展程序还是弹出上面这个弹窗，显示未登录状态

**Comment by sunoj** [comment]
在以访客默认或者隐藏模式打开chrome吗？在登录时选择了让京价保记住密码并自动登录吗？

**Comment by dsky1990** [comment]
正常模式，选择了，我看了，现在是登陆状态，但是每次都会提示登陆，是不是判断登陆态提示登陆的地方有问题

**Comment by pollywuhao** [comment]
同样的症状，之前好用啊，某一天开始突然不正常了，chrome版本 63.0.3239.132

**Comment by sunoj** [comment]
已修复，请更新：https://jjb.im/
