### ISSUE TITLE
希望增加 自营过滤功能

### ISSUE THREAD

**Issue by vmvz** [sunoj/jjb#34]
京东 自营会方便一些, 特别是售后, 

可惜官方系统的过滤很不好用, 希望能增加此功能

类似于: https://greasyfork.org/zh-CN/scripts/33729-%E4%BA%AC%E4%B8%9C%E8%87%AA%E8%90%A5%E8%BF%87%E6%BB%A4

**Comment by sunoj** [comment]
恩 好主意，可以考虑
