### ISSUE TITLE
LICENSE 使用错误

### ISSUE THREAD

**Issue by sbitpdc** [sunoj/jjb#36]
您所使用的 LICENSE 是没有任何法律效应的。可以参考 MIT或者 Apache 2 license。使用这些标准的才能具有法律效应

**Comment by sunoj** [comment]
请注意：京价保并非一个开源软件，并不以任何开源协议授予社区合法使用的权利。加入该 LICENSE 是由于有人提到京价保没有 LICENSE 文件让部分人误以为是以任何开源协议来发布的。

**Comment by sunoj** [comment]
请您理解， MIT 或者 Apache 2 license 是开源协议，而京价保作者保留所有权利，除非作者声明以某种协议开源，否则京价保在法律上所有的权利默认是属于作者。这是有法律效应，受中国和外国法律保护的。
