### ISSUE TITLE
订单跟踪不上

### ISSUE THREAD

**Issue by googooog** [sunoj/jjb#37]
1月18号以后的订单在最近订单里免显示不出来,没法保价,希望作者更新

**Comment by Utaha** [comment]
相同问题，我订单抓取停止在2018年1月20日

**Comment by pollywuhao** [comment]
相同问题

**Comment by sunoj** [comment]
确认问题 近期修复

**Comment by sunoj** [comment]
https://chrome.google.com/webstore/detail/%E4%BA%AC%E4%BB%B7%E4%BF%9D-%E4%BA%AC%E4%B8%9C%E4%BB%B7%E4%BF%9D%E5%8A%A9%E6%89%8B/gfgkebiommjpiaomalcbfefimhhanlfd
