### ISSUE TITLE
CRX文件无法下载

### ISSUE THREAD

**Issue by gygm** [sunoj/jjb#41]
下载链接显示 “Briefly unavailable for scheduled maintenance. Check back in a minute.HTTP/1.1 200 OK Content-Type: text/html; charset=UTF-8 Briefly unavailable for scheduled maintenance. Check back in a minute.nil”

**Comment by sunoj** [comment]
哪个下载链接？

**Comment by gygm** [comment]
就是在https://jjb.im/页面“下载CRX”这个链接https://www.crx4chrome.com/extensions/gfgkebiommjpiaomalcbfefimhhanlfd/

**Comment by sunoj** [comment]
这个页面的哪个下载链接？https://www.crx4chrome.com/crx/67270/ 这里这么多下载链接，每一个都不能用吗？
