### ISSUE TITLE
提示抢到了优惠券，但实际却没有

### ISSUE THREAD

**Issue by itsjoke** [sunoj/jjb#43]
提示抢到了优惠券，但实际却没有
比如：
¥88元 (满2018可用)  油卡充值中石油、壳牌商品

**Comment by Javalee** [comment]
是的 我也存在同样问题：
提示抢到了Plus 会员券，实际没有：
事实上查了下目前好像就没有这个卷的领取方式：
`¥40元 (满600可用) 全品类（特例商品除外)`
