### ISSUE TITLE
能否增加京东金融的签到

### ISSUE THREAD

**Issue by edsion1107** [sunoj/jjb#46]
https://home.jdpay.com/my/signIndex?from=singlemessage&isappinstalled=0&source=JDSC

京东金融里有个签到，我发现公众号里有真实的地址，每天至少一个钢镚。

另外，京东app和京东金融app最近一直有双签的奖励，看看是不是也能加上自动领取？

**Comment by sunoj** [comment]
新版已经加上了，双签好像必须在手机上面领取，目前没找到网页上领取的入口

**Comment by cc1024** [comment]
双签在这里
https://ljd.m.jd.com/countersign/index.action
