### ISSUE TITLE
自动登录是不是凉了

### ISSUE THREAD

**Issue by Germxu** [sunoj/jjb#48]
昨晚看到京东加了登录验证码, 这个自动登录的页面就一直卡在那里了, 需要自己手动填一下验证码登录

**Comment by sunoj** [comment]
最大可能性是你开了科学上网，不过下一版京价保会对这种情况做处理

**Comment by Germxu** [comment]
我是开了梯子的， 不过没有全局代理啊

**Comment by wankang99** [comment]
我最近也是这个情况，前几天装了个科学上网的插件，但是没开也要验证码，删了插件还是要验证码。。。。

**Comment by sunoj** [comment]
京东的政策是你异地登录就会出验证码。

**Comment by sunoj** [comment]
一次成功的登录之后一般短时间内就不会需要验证码了，本周末会更新一个版本特殊处理这个情况。

**Comment by wonzer** [comment]
已经更新到1.15.5。非常感谢 @sunoj 开发出如此NB实用的插件。

登陆这块，能否改成如果当前已登陆，就不需重复的自动登陆呢？

**Comment by axpwx** [comment]
@sunoj 京东的策略应该判断了UA的，UA是chrome，登录就会出现验证码，别的浏览器不会，你验证一下，可以伪造UA为别的浏览器来绕过这个限制。

**Comment by sunoj** [comment]
@axpwx 感谢提供思路，本周末我验证一下

**Comment by yimiaodaren** [comment]
我是mac chrome 登陆成功了，但是点开就说我 京价保未能获取登录状态 。 但是其他设置里面是有密码的，是显示清除已保存的密码的

**Comment by yimiaodaren** [comment]
ActiveXObject is not definedActiveX
