### ISSUE TITLE
为什么插件用不了,

### ISSUE THREAD

**Issue by yanjianye2018** [sunoj/jjb#50]
没有爬墙,无限弹这个界面
![qq 20180318182437](https://user-images.githubusercontent.com/37500177/37564881-bdf4852a-2ad9-11e8-8dc8-ddafd52ffc24.png)
没有爬墙,不会签到领豆子优惠券,会出验证码,偶尔能领到钢镚
![qq 20180318182741](https://user-images.githubusercontent.com/37500177/37564903-2a8dbb48-2ada-11e8-8b9d-fbb968198306.png)

**Comment by sunoj** [comment]
请写清楚遇到问题的原因，浏览器和操作系统环境，重现的流程。 如果有开发能力，建议在本地调试出出错的代码。

**Comment by yanjianye2018** [comment]
浏览器是chrome的,系统是win7 64位旗舰版的,没开发能力,可以的话远程帮帮忙,我刷新浏览店铺签到现在只会登陆到我的京豆那个页面
