### ISSUE TITLE
Enable该扩展后，导致google-chrome闪退

### ISSUE THREAD

**Issue by jemyzhang** [sunoj/jjb#52]
Chrome: 版本 65.0.3325.162（正式版本） （64 位）
System: ubuntu 1710

Chrome今天经常SEGV, 经过排查，发现是由本扩展导致。
扩展安装自chrome商店。

本扩展以前没用过，不知道对于chrome老版本有没有相同问题。

没有太具体的log可以看，如果有需要，可以贴上系统crash文件（比较大，35M）。

**Comment by sunoj** [comment]
之前有人反馈过，本拓展不支持 ubuntu 系统

**Comment by jemyzhang** [comment]
@sunoj 好吧，挺好的原因^^

刚才单独测试了一下，当运行“**精选优惠券**”时，浏览器立马stall然后退出。

**Comment by sunoj** [comment]
我本人没有在使用 ubuntu 所以不好调试问题，如果你有开发能力，可以自己 fork 以后尝试解决一下

**Comment by jemyzhang** [comment]
ok, 有空的话，我尝试看看

PS. 谢谢你的插件. 已打赏^^

**Comment by sunoj** [comment]
感谢

**Comment by jemyzhang** [comment]
@sunoj 
目前看来，用iframe方式打开“领白条券”或者“精选优惠券”页面时，会出现崩溃的问题。具体原因不知道，没有这方面的知识。如果直接tab打开，则一切正常

```
$("#iframe").attr('src', "https://plogin.m.jd.com/user/login.action?appid=100&kpkey=&returnurl=https%3A%2F%2Fcoupon.m.jd.com%2Fcenter%2FgetCouponCenter.action")
```
