### ISSUE TITLE
京价宝在Linux Chrome上是否有兼容问题呢？

### ISSUE THREAD

**Issue by kslr** [sunoj/jjb#69]
你好 sunoj

我有三台linux设备，系统分别为ubuntu和arch。
浏览器分别为chrome和chromium的最新稳定版和开发测试版。
最近这几个月偶尔会遇到浏览器崩溃的问题，这个情况在工作5个小时以上时偶遇。
这段时间通过无profile运行和插件逐一测试，发现禁用京价宝成功连续运行了三天以上。
同时，我使用chrome dev stote 在firefox上迁移了插件，工作稳定。

根据日志大部分提示socket_stream.cc被close -100
这是否和定时控制器有关呢？
我该如何深入排查？

**Comment by sunoj** [comment]
是的 京价保似乎在linux下有明确的兼容问题，受到大量不兼容linux的反馈。但由于我本人没有任何linux设备，因此京价保目前不支持linux。
根据其他人的反馈，似乎和 background 中的 iframe 有关，供参考。

**Comment by kslr** [comment]
@sunoj 我建议在README标注一下这个问题，避免一些人重走弯路。

**Comment by sunoj** [comment]
感谢建议，官网常见问题中有说明：https://jjb.im/，下次我在 README 里面也说明一下。
