### ISSUE TITLE
精选优惠券无法执行

### ISSUE THREAD

**Issue by cold-snap** [sunoj/jjb#71]
Chrome66.0.3359.181 自从四月份以来从来没有执行过精选优惠券，手动运行也没有效果

**Comment by twomaos** [comment]
我也有一样的情况, **精选优惠券**和**京东会员签到**从未执行. 其他的都正常.

**Comment by sunoj** [comment]
是不是因为没有保存密码呢

**Comment by twomaos** [comment]
我保存了密码, 还是不行. 手动点刷新键领取也没有反应. 其他的功能正常.

**Comment by cold-snap** [comment]
我也一样，能签到但是执行不了优惠券，即便是手动刷新也不行

**Comment by sunoj** [comment]
如何判断的执行不了优惠券，须知除了签到以外其他任务没有绿色的完成勾的

**Comment by sunoj** [comment]
确认精选优惠券由于京东页面改动的原因确实失效了，下一版更新。

**Comment by cold-snap** [comment]
好的 麻烦您啦
