### ISSUE TITLE
机器是MBP，开启后chrome的任务管理器cpu占用高，风扇一直在响

### ISSUE THREAD

**Issue by xiaoyaojones** [sunoj/jjb#72]
机器是新的17款13寸MBP i5 2.3G，
chrome启用京保价后一段时间cpu占用就一直居高不下，风扇响得厉害。
macos版本：10.13.4
chrome版本：版本 67.0.3396.62（正式版本） （64 位）

cpu占用如下图：
![image](https://user-images.githubusercontent.com/3916186/40783285-8f90313c-6514-11e8-90ae-bc2d184e3919.png)

**Comment by sunoj** [comment]
感谢反馈，我也刚升级到 chrome  67 目前没有观察到你遇到的情况，有待继续观察和更多反馈

**Comment by sunoj** [comment]
基本确认了这个问题，会尽快更新解决。

**Comment by jifeng** [comment]
你好，方便问下是什么原因造成的吗？

**Comment by sunoj** [comment]
@jifeng 同样作为技术人员，希望你能理解调查问题的原因是需要投入相当的时间的。目前我调查的结果倾向于认为这是一个 chrome 新版的 bug， 详见：https://www.reddit.com/r/chrome/comments/8njj4d/huge_cpu_usage_in_chrome_67/

**Comment by sunoj** [comment]
已更新 1.16.0 解决

**Comment by jifeng** [comment]
这个理解，我们昨天也是网站也是遇到类似的问题，排查之后发现是 chrome 67版本中的同步ajax加载有问题，会造成cpu飙升了。具体可以用这个方式复现
```
var xmlhttp = new XMLHttpRequest; 
xmlhttp.open("GET", document.location.href, false); 
xmlhttp.send(); 
if (xmlhttp.readyState == 4) {
    console.log(xmlhttp.readyState);
}
```
把网站中涉及到同步的改成异步就好。
具体可参见：
- [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=848210)
- [代码修复](https://chromium-review.googlesource.com/c/chromium/src/+/1081777/5/third_party/blink/renderer/platform/loader/fetch/fetch_parameters.cc#133)

新版的chrome已经在修复这个问题，但还没有正式发布
希望对你也有所帮助
