### ISSUE TITLE
请问是否可以选择仅提示价保但是不自动申请

### ISSUE THREAD

**Issue by EraserKing** [sunoj/jjb#73]
考虑到以下几个情况：
1. 多台电脑上均安装，可能会重复申请价保
2. 自动申请价格保护的退款路径不可选（通常原返，但是电话客服申请时一般可以自选），原路退回可能会计做退款（对各类支付活动有影响）

因此，想询问是否有计划，在检测到价格变动时，仅提示有潜在价保，并让用户手动操作

谢谢

**Comment by sunoj** [comment]
建议很好，有道理。未来会考虑。

但是功能建议请使用插件内的建议反馈，不要开 issues。
