### ISSUE TITLE
Opera每隔一段时间就会弹出这个提示

### ISSUE THREAD

**Issue by raofeng** [sunoj/jjb#74]
![image](https://user-images.githubusercontent.com/4425569/41388708-c91b1c2c-6fbf-11e8-8e93-c8ed2cae1cf8.png)
是领取优惠券引起的问题？

**Comment by sunoj** [comment]
看样子是领取白条券引起的，我研究一下

**Comment by popstk** [comment]
win10 opera 一直都有这个问题

**Comment by sunoj** [comment]
1.16.3 已解决
