### ISSUE TITLE
Shadowsocks冲突问题

### ISSUE THREAD

**Issue by rlad2333** [sunoj/jjb#76]
Win7-64bit
shadowsocks 4.0.10 客户端，PAC 模式

插件开启情况下，登录3.cn京东，弹出提示：请将插件排除科学上网。
不开SS，无问题。

chrome 及插件商店本身都是走的SS，单独排除京价保不知如何设置？
多谢！

**Comment by sunoj** [comment]
“请将插件排除科学上网” 不是京价保提示的，请复查
