### ISSUE TITLE
增加手动开关

### ISSUE THREAD

**Issue by quericy** [sunoj/jjb#8]
感谢作者的努力，功能很强大！
但是领券功能一开就领一堆，不太敢用

建议：
增加手动模式的开关,在手动模式下
展示可领券列表,可申请价保的列表等等。。。
手动选择需要的券和商品 触发领取和申请价保

一来可以不用领太多不需要的券，二来降低被黑号的风险

**Comment by sunoj** [comment]
但是手动模式听起来....似乎跟直接自己手动领取和申请价保是一样的啊.....

**Comment by quericy** [comment]
@sunoj 区别在于，收集到可用的数据时扩展弹出消息通知，是否领取是人工可筛选的。
或者自动按设定好的感兴趣的品类筛选(不过这样就相对复杂了)
