### ISSUE TITLE
价格保护功能无法使用

### ISSUE THREAD

**Issue by cnzz** [sunoj/jjb#81]
最近价格保护功能无法使用
chrome浏览器
版本 67.0.3396.99（正式版本） （64 位）
手动触发刷新也无法执行价格保护功能
![image](https://user-images.githubusercontent.com/5003577/42429290-bca3df24-836a-11e8-9f5e-90e8b7afe486.png)

**Comment by sunoj** [comment]
如何判断的无法执行呢？

**Comment by cnzz** [comment]
谢谢回复
有符合价格保护的商品, 手动刷新京价保中的"价格保护"却没有执行价格保护.
后来我去京东后台点"申请价保"就成功了
![image](https://user-images.githubusercontent.com/5003577/42429660-f0a6d81a-836c-11e8-910e-32cc726a3136.png)
