### ISSUE TITLE
使用chromium存在浏览器直接自动卡死，然后退出

### ISSUE THREAD

**Issue by konghui** [sunoj/jjb#82]
我先使用的时候经常会出现浏览器直接卡死，然后点什么都没有反映，最后直接退出了。我手动点击运行任务的任务里面就会触发这个问题，浏览器版本是：
Version 67.0.3396.87 (Official Build) Arch Linux (64-bit)

**Comment by sunoj** [comment]
是的 在 Linux 下问题很明显

**Comment by konghui** [comment]
有办法解吗，知道什么问题吗？还是chromium本身的问题？
