### ISSUE TITLE
显示关闭领券后仍会自动领券

### ISSUE THREAD

**Issue by haodong** [sunoj/jjb#86]
![wx20180716-181845](https://user-images.githubusercontent.com/8103074/42755391-8d46ff2a-892a-11e8-8bb0-83cba14f86ec.jpg)

**Comment by sunoj** [comment]
调查中...

**Comment by haodong** [comment]
@sunoj 好的。这个问题之前是没有的，是升级、重装系统之后出现的。

**Comment by haodong** [comment]
今天早上还是老样子默认领券。我想了想，尝试先将2、3、4功能开启2小时一次、5小时一次，再关闭。一早上都清净了。
谁知道，刚才检测到一次保价机会，触发之后立刻给我领了一堆券，还包括一张游轮。。。
![1](https://user-images.githubusercontent.com/8103074/42922053-9202ab8a-8b51-11e8-92e6-88b39e2dab1d.jpg)

**Comment by sunoj** [comment]
已在 1.17.0 中修复
