### ISSUE TITLE
能不能加个签到失败后的邮件提醒功能?

### ISSUE THREAD

**Issue by fcying** [sunoj/jjb#87]
这样挂在nas 上用, 如果登录失败的话, 也能及时知道.
不用每天去看一眼

**Comment by sunoj** [comment]
不具可行性，京价保作为一个纯客户端软件，没有发送邮件的能力，若需增加，则需增加服务器业务。

**Comment by fcying** [comment]
不需要增加服务器业务啊? 自己填写要用哪个邮件服务器的stmp地址, 账号密码, 接收端的邮件地址, 调用个接口就可以发送邮件了吧?

**Comment by sunoj** [comment]
这确实是一个思路，但这个功能过于小众，建议自己实现，也欢迎你实现之后发PR。

**Comment by sunoj** [comment]
另外似乎没有找到在chrome插件中实现一个利用stmp或pop3协议的邮件发送功能的先例，建议你可以调研一下是否有可行方案，是否成本适当。

**Comment by fcying** [comment]
查了下 方便的办法只有一个调用本地客户端, 这个就好麻烦了.....
本来还以为和python 一样....直接写个几行就行了...

**Comment by fcying** [comment]
另外请教一下....chrome插件 有写本地文件的权限吗?  如果可以根据运行log 判断的话....我可以弄个外部的python 脚本去实现....

**Comment by lotosbin** [comment]
@sunoj 可以提供类似webhooks，有通知时调用指定的地址，通知可以由使用者自己实现，

**Comment by sunoj** [comment]
各位提供的思路非常好 欢迎 PR  @lotosbin @aidevjoe
