### ISSUE TITLE
每次登陆账号后，只有当天会签到领券，第二天就失效了

### ISSUE THREAD

**Issue by whiskey0705** [sunoj/jjb#88]
如题，每次登陆账号后，只有当天会签到领券，第二天就失效了。删掉扩展重新安装又能正常工作一天。

PS:账号已经选择记住，win10LTSB版

**Comment by sunoj** [comment]
请问浏览器版本是？第二天就失效是指？

**Comment by whiskey0705** [comment]
你好，浏览器上chrome最新稳定版，失效是指不会自动签到了。需要卸载了再安装才能用，但是第二天又要重复上述操作。
只有在第一次购买了的时候 差不多工作了一星期，接下来都是这种奇葩情况。。

**Comment by haodong** [comment]
![screen shot 2018-07-23 at 12 36 01 am](https://user-images.githubusercontent.com/8103074/43047858-80210094-8e10-11e8-9de7-e985d24fe9eb.png)

是的。
更新后的版本，开启的功能就干脆不工作了。如图可见日志。

**Comment by sunoj** [comment]
1.17.1 应该已经解决掉这个问题，更新后观察一下试试。

**Comment by mrdea** [comment]
同样出现这个问题
Mac 10.13.6 (17G65)
Chrome Version 68.0.3440.106 (Official Build) (64-bit)
jjb 1.17.3
