### ISSUE TITLE
链接跳转无线死循环

### ISSUE THREAD

**Issue by gotounix** [sunoj/jjb#93]
使用插件后，在第三方网站，比如：百度搜索结果、什么值得买，点击链接跳转的时候经常出现死循环，整个浏览器卡死，链接无限跳转。
禁用扩展后没有此问题。

操作系统：Windows 10
浏览器：Firefox 62.0b12 (64 位)

**Comment by sunoj** [comment]
百度搜索结果举例说一下，另外挂上代理试一下，看是不是运营商劫持导致的

**Comment by sunoj** [comment]
另外你用的京价保的版本是多少？

**Comment by gotounix** [comment]
抱歉，刚刚提供的信息不完整。
我刚刚挂代理测试了下，应该不是运营商劫持。
我在浏览器中直接输入：http://item.jd.com/2953318.html，就不能打开，无限跳转，页面空白，关闭扩展，可以打开。
京价保版本：京价保 - 京东价保助手 1.17.1（来自：https://addons.mozilla.org/zh-CN/firefox/）

**Comment by sunoj** [comment]
确认问题了，在 Firefox 62 下面确认有问题，会尽快修复。不过这个版本目前应该不是稳定版？

**Comment by gotounix** [comment]
我一直是用beta通道，这个问题持续很长时间了，谢谢。

**Comment by sunoj** [comment]
已更新 1.17.3 解决
