### ISSUE TITLE
恭喜我喜提京东黑号一个……

### ISSUE THREAD

**Issue by cnBruceHong** [sunoj/jjb#96]
大家还是把领券功能关一关……

**Comment by sunoj** [comment]
黑号的具体体现是什么？是因为京价保领券不成功吗？这个问题目前调查是京东的风控似乎对移动端领券有一定的限制。但是同一个账号在网页端和手机APP端还是可以领券，证明账号并未异常。

另外，这是一个什么 issue？

**Comment by cnBruceHong** [comment]
表现为目前涉及的所有全品类券，无论在哪种平台下都是领取不了状态。
插件是个好插件，希望作者能把领券条件增强下。

**Comment by sunoj** [comment]
具体哪一张或几站券不能领取？提示是什么？是否联系过客服询问原因？近期有没有大件商品拒收或退货？

**Comment by sunoj** [comment]
领券功能需要如何强化呢？有什么实施想法？欢迎发 Pull Request

**Comment by lanceli** [comment]
我也黑了 已把领券功能关了。 暂时还不知道 是否跟其他功能相关 @cnBruceHong

**Comment by sunoj** [comment]
@lanceli  黑号具体表现是什么能方便告知一下吗？领券功能早已移除，是否没有更新到最新版？

**Comment by lanceli** [comment]
![img_3746](https://user-images.githubusercontent.com/874744/44704311-6c7dc700-aacd-11e8-8769-f429067f86ab.PNG)
![img_3745](https://user-images.githubusercontent.com/874744/44704314-70114e00-aacd-11e8-8a53-80d2c69b3c4a.PNG)

现在看是微信的京东领券中心领不了。返利的京东券领不了。 之前还有个京东的一元活动参加不了,具体什么提示记不清了。

更新了 现在是1.18.2

我把plus券和白条券也关闭了

说自己黑号其实也是自己定义的 没问过客服。 插件还是不错的。我也没法判断领不了券跟插件是否有关系 。🤦‍♂️

**Comment by sunoj** [comment]
@lanceli 1.18.3 才是最新版，而且已经发布一周多了，应该早就自动更新了才对。 你的情况是触发了京东的风控，移动网页端（包括微信端、M站）被限制领券了，但是京东App 和 网页端应该是正常的？

**Comment by lanceli** [comment]
@sunoj 刚更到1.18.3了 app刚看是正常的。之前记不太清刚封的时候app领券是否正常了，理论上我应该都试过。

@cnBruceHong 有的。搞活动带爱奇艺的plus

**Comment by cnBruceHong** [comment]
@lanceli 我这边问了下，是这个活动的原因，和插件无关。

**Comment by lanceli** [comment]
@cnBruceHong 意思是带爱奇艺88的plus不能领券了？

**Comment by lanceli** [comment]
@cnBruceHong dang s当时是这个活动也不能参加
![2711535519657_ pic](https://user-images.githubusercontent.com/874744/44766728-7109b480-ab8d-11e8-9f12-b8a1250dade8.jpg)

**Comment by wang93wei** [comment]
哈哈，我也黑号了，不过不影响啊。我感觉可能是我买iPhone Xs Max用了返利网+增值税发票？
