### ISSUE TITLE
金融会员签到的问题

### ISSUE THREAD

**Issue by wellkens** [sunoj/jjb#97]
更新了新版之后，在：
https://vip.jr.jd.com
这个页面虽然能签到，但显示的是获得20钢镚儿，但实际上是20天之后钢镚儿到账，希望修正

**Comment by sunoj** [comment]
已知问题，下一版修改

**Comment by sunoj** [comment]
@whiskey0705  你的反馈和当前的问题无关，而且未包含任何详情，请在应用内反馈或发送邮件反馈。请勿破坏问题反馈秩序。

**Comment by whiskey0705** [comment]
> @whiskey0705 你的反馈和当前的问题无关，而且未包含任何详情，请在应用内反馈或发送邮件反馈。请勿破坏问题反馈秩序。

不好意思，原问题已经被关闭，但实际上新的版本又出现了。
这是[问题](https://github.com/sunoj/jjb/issues/88#issuecomment-407001746)链接

**Comment by sunoj** [comment]
已恢复
