### ISSUE TITLE
移动网页登录失效 无法使用价保

### ISSUE THREAD

**Issue by 474364707** [sunoj/jjb#99]
在京东打开商品链接会自动跳转到
该商品手机版网页
多次尝试无法解决该问题
清空有关京东所有的Cookie之后
跳转正常
移动网页提示登录失败

**Comment by 474364707** [comment]
![tim 20180820034910](https://user-images.githubusercontent.com/34829455/44312518-28156b80-a3e9-11e8-9477-9c5f212f293c.jpg)
![tim 20180820034532](https://user-images.githubusercontent.com/34829455/44312519-2a77c580-a3e9-11e8-9515-a1f40b4cafc6.jpg)

**Comment by 474364707** [comment]
已解决

**Comment by sunoj** [comment]
确实有问题 1.18.1已修复

**Comment by draguo** [comment]
windows 下的 chrome 现在出现了同样的问题，已重装，无效。

**Comment by sunoj** [comment]
@draguo 因为京东网页更新，目前确实判断失效的问题，今天会马上更新一个版本来解决
